@extends('layouts.public')
@section('title','Hospedagem e serviços')
@section('body-class','homepage')
@section('content')
<section class="home-hero"><div class="home-hero-copy"><span class="hero-tag"><span></span> {{ $home['eyebrow'] }}</span><h1>{{ $home['title'] }}</h1><p>{{ $home['description'] }}</p><div class="home-hero-actions"><a class="btn btn-primary" href="#planos">{{ $home['cta'] }} {!! panel_icon('chevron',19) !!}</a><a class="home-text-link" href="{{ route('login') }}">Já sou cliente {!! panel_icon('chevron',16) !!}</a></div><div class="hero-trust"><span>{!! panel_icon('shield',17) !!} Acesso protegido</span><span>{!! panel_icon('settings',17) !!} Gestão centralizada</span></div></div>
<div class="home-illustration" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="orbit-dot"></div><div class="cloud-console"><div class="console-top"><span class="console-dots"><i></i><i></i><i></i></span><span>SEU ESPAÇO DIGITAL</span>{!! panel_icon('shield',16) !!}</div><div class="console-body"><div class="console-title"><span class="console-icon">{!! panel_icon('cloud',27) !!}</span><div><strong>Ideias sem limites.</strong><small>Mais controle, menos complicação.</small></div></div><div class="server-rack"><span>{!! panel_icon('server',30) !!}</span><div><b>Seu próximo projeto</b><small>Um lugar para começar</small></div><span class="rack-lights"><i></i><i></i><i></i></span></div><div class="server-rack"><span>{!! panel_icon('globe',30) !!}</span><div><b>Seu mundo conectado</b><small>Tudo em um só painel</small></div><span class="rack-lights"><i></i><i></i><i></i></span></div><div class="console-mini-grid"><span>{!! panel_icon('store',20) !!} Contrate</span><span>{!! panel_icon('monitor',20) !!} Gerencie</span><span>{!! panel_icon('ticket',20) !!} Acompanhe</span></div></div></div><div class="floating-badge badge-cloud">{!! panel_icon('zap',21) !!}<div><strong>Pronto para o próximo passo?</strong><small>Seu projeto começa com uma escolha.</small></div></div><div class="floating-icon">{!! panel_icon('cloud',32) !!}</div></div></section>
<div class="home-value-strip"><span>DO PRIMEIRO PASSO<br><strong>à gestão do dia a dia.</strong></span><div>{!! panel_icon('server',24) !!} Seus serviços</div><div>{!! panel_icon('invoice',24) !!} Suas faturas</div><div>{!! panel_icon('ticket',24) !!} Seu atendimento</div><div>{!! panel_icon('user',24) !!} Sua conta</div></div>
<section class="home-section" id="planos"><div class="home-section-head"><div><span class="eyebrow">ENCONTRE SEU ESPAÇO</span><h2>Um plano para o seu próximo passo.</h2><p>Compare as opções disponíveis e escolha o que faz sentido para você.</p></div><a class="home-text-link" href="{{ route('store') }}">Explorar todos os planos {!! panel_icon('chevron',17) !!}</a></div><div class="home-plans">
@forelse($products as $p)<article class="home-plan"><span class="settings-tile-icon tone-violet">{!! panel_icon('server',25) !!}</span><h3>{{ $p->name }}</h3><p class="plan-description">{{ Str::limit($p->description,180) }}</p><div class="plan-price">{{ brl($p->price_minor) }}<small>{{ \App\Support\Cycle::LABELS[$p->cycle]??$p->cycle }}</small></div>@if($p->setup_minor)<p class="muted">Instalação: {{ brl($p->setup_minor) }}</p>@endif<a class="btn {{ $loop->first?'btn-primary':'btn-ghost' }} btn-block" href="{{ route('store') }}">{{ $p->stock===0?'Ver disponibilidade':'Ver plano e opções' }} {!! panel_icon('chevron',17) !!}</a><small class="plan-note">Confira recursos e condições no catálogo.</small></article>
@empty<div class="home-plan home-plan-empty">{!! panel_icon('store',35) !!}<h3>Novos planos a caminho.</h3><p>Consulte nosso catálogo ou entre em contato para conhecer as opções disponíveis.</p><a class="btn btn-primary" href="{{ route('store') }}">Abrir catálogo</a></div>@endforelse
</div></section>
<section class="home-section home-benefits" id="experiencia"><div class="home-benefits-intro"><span class="eyebrow">MENOS COMPLICAÇÃO</span><h2>Cuide do seu projeto.<br>Tenha o resto à mão.</h2><p>Da contratação ao atendimento, organize sua experiência em uma única conta.</p><a class="home-text-link" href="{{ route('login') }}">Conheça sua área do cliente {!! panel_icon('chevron',17) !!}</a></div><div class="home-benefit-grid">@foreach([['monitor','Tudo no seu painel','Acompanhe seus serviços e pedidos sem se perder entre ferramentas.'],['invoice','Faturas organizadas','Consulte valores, vencimentos e os meios de pagamento disponíveis.'],['ticket','Converse com a equipe','Abra solicitações e acompanhe o histórico dos seus atendimentos.'],['shield','Segurança nas suas mãos','Proteja sua conta com senha e autenticação em duas etapas.']] as [$icon,$title,$text])<article><span class="settings-tile-icon tone-violet">{!! panel_icon($icon,23) !!}</span><h3>{{ $title }}</h3><p>{{ $text }}</p></article>@endforeach</div></section>
<section class="home-section home-faq" id="duvidas"><div><span class="eyebrow">ANTES DE COMEÇAR</span><h2>Vamos tirar suas dúvidas.</h2><p>Não encontrou o que procura? <a href="{{ route('knowledge.index') }}">Visite a central de ajuda.</a></p></div><div>@foreach([['Como contrato um plano?','Acesse o catálogo, confira as opções, entre na sua conta e finalize o pedido. A ativação segue as condições do plano e a confirmação do pagamento.'],['Onde acompanho meus serviços?','Na área do cliente você encontra serviços, faturas e solicitações de atendimento reunidos na mesma conta.'],['Posso entrar com uma conta social?','Sim, quando habilitados pela administração, os provedores disponíveis aparecem na tela de login. Para uma conta existente, entre primeiro com sua senha e faça o vínculo em Minha conta.'],['Como entro em contato com a equipe?','Clientes podem abrir uma solicitação pela área de suporte. O contato público, quando configurado, também aparece no rodapé do site.']] as [$question,$answer])<details><summary>{{ $question }}<span>+</span></summary><p>{{ $answer }}</p></details>@endforeach</div></section>
<section class="home-final-cta"><div><span class="eyebrow">O PRÓXIMO PASSO É SEU</span><h2>Vamos dar espaço à sua ideia?</h2><p>Explore os planos e encontre seu lugar para começar.</p></div><a class="btn btn-light" href="{{ route('store') }}">Escolher meu plano {!! panel_icon('chevron',18) !!}</a></section>
@endsection
