@extends('layouts.public')
@section('title','Privacidade e contas conectadas')
@section('content')
<article class="card wrap narrow"><span class="eyebrow">TRANSPARÊNCIA</span><h1>Privacidade e contas conectadas</h1><p>Esta página descreve o tratamento técnico do login social nesta instalação de {{ config('app.name') }}. Consulte também as <a href="{{ route('terms') }}">condições da instalação</a> e as políticas comerciais informadas pelo operador.</p>
<h2>O que usamos para o login</h2><p>Quando você autoriza um provedor, recebemos um identificador da conta e, quando disponibilizados, nome e e-mail. Nome e e-mail são apresentados para sua confirmação no cadastro. A conta local guarda o vínculo entre o identificador e o provedor. Não guardamos os tokens de acesso ou renovação do provedor e não importamos suas publicações, contatos ou arquivos.</p>
<h2>Sua autorização e a segurança da conta</h2><p>O login social é opcional. Usamos cookies essenciais de sessão para manter sua autenticação e proteger o retorno do provedor. Contas com e-mails iguais não são unidas automaticamente. Para vincular uma conta existente, entre com sua senha e confirme em Minha conta. A autenticação em duas etapas continua sendo exigida quando cadastrada.</p>
<h2 id="exclusao">Remover um vínculo ou solicitar exclusão</h2><ol><li>Entre no painel e abra <strong>Minha conta → Contas conectadas</strong>.</li><li>Escolha o provedor, confirme sua senha e o código de duas etapas quando solicitado e clique em <strong>Desconectar conta</strong>. Isso remove o vínculo armazenado neste painel.</li><li>Para revogar a autorização no provedor, remova também o aplicativo nas configurações de aplicativos conectados do Google, GitHub, X, Facebook ou Microsoft.</li><li>Para solicitar exclusão da conta local e análise dos demais dados, entre em contato com o operador pelos canais abaixo. Desconectar um provedor não cancela serviços, apaga faturas nem elimina registros de transações. O operador deverá informar quais dados precisam ser conservados e os motivos aplicáveis.</li></ol>
<p><a href="{{ route('tickets.index') }}">Abrir solicitação ao atendimento</a>@if(config('site.support_email')) ou escrever para <a href="mailto:{{ config('site.support_email') }}">{{ config('site.support_email') }}</a>@endif.</p><p class="muted">O responsável por esta instalação deve manter seus dados de contato e sua política comercial atualizados e avaliar os requisitos legais e dos provedores antes de habilitar o login social.</p></article>
@endsection
