"""LOCAL Pterodactyl + Ollama UI regression. Providers are intercepted by CLI fixtures.
Catalog POST is a browser test interception invoking the real local controller with Http::fake;
full route authorization is covered in PHPUnit. No provider credentials/real services are used.
"""
import json,os,re,subprocess,uuid,sys,ipaddress
from pathlib import Path
from urllib.parse import urlparse
from playwright.sync_api import sync_playwright,expect
ROOT=Path(__file__).resolve().parents[1];BASE=os.environ.get('LAGOS_TEST_URL','http://127.0.0.1:8080');F=json.loads((ROOT/'.cache/demo.json').read_text());suffix=uuid.uuid4().hex[:8]
assert urlparse(BASE).scheme=='http' and (urlparse(BASE).hostname=='localhost' or ipaddress.ip_address(urlparse(BASE).hostname).is_loopback)
(ROOT/'docs/BROWSER-PTERO-AI-RESULTS.json').unlink(missing_ok=True)
def fixture(*args):return json.loads(subprocess.run(['php','tests/ptero-ai-fixture.php',*map(str,args)],cwd=ROOT,env=dict(os.environ,LAGOS_TEST_MODE='1'),capture_output=True,text=True,check=True).stdout)
results=[];errors=[]
def check(label,ok):results.append({'test':label,'passed':bool(ok)});print(('PASS 'if ok else'FAIL ')+label)
with sync_playwright()as pw:
 b=pw.chromium.launch(headless=True,args=['--no-sandbox']);ctx=b.new_context(viewport={'width':1440,'height':1000},extra_http_headers={'X-Forwarded-For':'192.0.2.47'});p=ctx.new_page();p.on('pageerror',lambda e:errors.append(str(e)))
 def go(path):r=p.goto(BASE+path);check('HTTP '+path,r.status==200);return r
 def login(email):
  go('/entrar');p.locator('[name=email]').fill(email);p.locator('[name=password]').fill(F['password']);p.get_by_role('button',name='Entrar',exact=True).click();p.wait_for_url('**/painel')
 def logout():p.locator('form[action$="/sair"] button').click()
 login(F['admin']);go('/admin/integracoes');form=p.locator('form[action$="/admin/integracoes"]');name='Pterodactyl '+suffix;form.locator('[name=name]').fill(name);form.locator('[name=driver]').select_option('pterodactyl');form.locator('[name=endpoint]').fill('https://ptero-fixture.invalid');form.locator('[name=token]').fill('ptero-fake-key-'+suffix);form.locator('[name=active]').check();form.locator('[name=ack_native]').check();form.get_by_role('button',name='Cadastrar integração',exact=True).click();check('Pterodactyl cadastrado com chave oculta',name in p.locator('body').inner_text() and 'ptero-fake-key-'+suffix not in p.content())
 link=p.get_by_role('link',name='Contas Pterodactyl — '+name,exact=True);link.click();check('Tela de vínculos acessível pelo ADM','Vincular conta' in p.locator('body').inner_text());p.locator('[name=user_id]').fill(str(fixture('client')));p.locator('[name=remote_user_id]').fill('41');p.locator('[name=ack]').check();p.get_by_role('button',name='Vincular conta',exact=True).click();check('Conta remota vinculada','Vínculo registrado' in p.locator('body').inner_text())
 go('/admin/produtos');form=p.locator('form[action$="/admin/produtos"]');product='Jogo Ptero '+suffix;form.locator('[name=name]').fill(product);form.locator('[name=slug]').fill('ptero-'+suffix);form.locator('[name=price]').fill('12,00');form.locator('[name=connector_id]').select_option(label=name);form.get_by_role('button',name='Salvar produto',exact=True).click();check('Plano Pterodactyl salvo','Produto salvo' in p.locator('body').inner_text());row=p.locator('tr').filter(has_text=product);pid=int(re.search(r'/produtos/(\d+)/',row.get_by_role('link',name='Editar',exact=True).get_attribute('href'))[1]);logout()
 login(F['client']);go('/loja');form=p.locator(f'form:has(input[name=product_id][value="{pid}"])');n=1
 while not form.count() and n<60:n+=1;go('/loja?page='+str(n));form=p.locator(f'form:has(input[name=product_id][value="{pid}"])')
 form.get_by_role('button',name='Adicionar ao carrinho',exact=True).click();p.wait_for_url('**/painel/carrinho');p.get_by_role('button',name='Finalizar pedido',exact=True).click();p.wait_for_url('**/painel/faturas/*');iid=int(p.url.rsplit('/',1)[-1]);check('Pedido de jogo gera cobrança correta','R$ 12,00' in p.locator('.invoice-total').inner_text());logout()
 login(F['admin']);go('/admin/faturas');form=p.locator(f'form[action$="/faturas/{iid}/confirmar"]');form.locator('[name=note]').fill('Pagamento fictício Pterodactyl');form.locator('button').click();go('/admin/servicos');card=p.locator('.card').filter(has=p.get_by_role('heading',name=re.compile(re.escape(product))));sid=int(re.search(r'/servicos/(\d+)',card.locator('form').get_attribute('action'))[1]);created=fixture('ptero',sid);check('Instalação assíncrona não ativa prematuramente',created['status']=='pending' and created['operation']=='review');installed=fixture('installed',sid);check('Consulta posterior ativa sem criar novamente',installed['status']=='active' and installed['calls'].count('POST /api/application/servers')==1)
 for state,expected in [('suspended','suspended'),('active','active'),('cancelled','cancelled')]:
  p.reload();card=p.locator('.card').filter(has=p.get_by_role('heading',name=re.compile(re.escape(product))));form=card.locator('form');form.locator('[name=status]').select_option(state);form.locator('[name=note]').fill('Lifecycle fictício Pterodactyl');
  if state=='cancelled':form.locator('[name=confirm_termination]').check()
  form.get_by_role('button',name='Confirmar ação',exact=True).click();result=fixture('ptero',sid);check('Pterodactyl '+expected,result['status']==expected and result['operation']=='done')
 go('/admin/integracoes/ollama');p.locator('[name=endpoint]').fill('https://ollama-fixture.invalid');p.locator('[name=token]').fill('ollama-fake-key-'+suffix);p.locator('[name=active]').uncheck();p.get_by_role('button',name='Salvar configuração Ollama').click();check('Chave Ollama salva sem ser revelada','Configuração salva' in p.locator('body').inner_text() and 'ollama-fake-key-'+suffix not in p.content())
 def catalog(route):
  models=fixture('models');check('Catálogo consultado via controlador com transporte simulado',models['models']==['suporte-fixture:large','suporte-fixture:small']);route.fulfill(status=303,headers={'Location':BASE+'/admin/integracoes/ollama'},body='')
 ctx.route('**/admin/integracoes/ollama/modelos',catalog);p.get_by_role('button',name='Consultar modelos com a chave salva').click();expect(p.locator('[name=model] option[value="suporte-fixture:small"]')).to_have_count(1);ctx.unroute('**/admin/integracoes/ollama/modelos',catalog)
 p.locator('[name=model]').select_option('suporte-fixture:small');p.locator('[name=active]').check();p.locator('[name=ack]').check();p.get_by_role('button',name='Salvar configuração Ollama').click();check('Modelo selecionado e chat habilitado','Habilitado' in p.locator('body').inner_text() and p.locator('[name=model]').input_value()=='suporte-fixture:small');logout()
 login(F['client']);p.get_by_role('link',name='Chat com IA',exact=True).click();check('Chat explica IA, privacidade e suporte humano','Não envie senhas' in p.locator('body').inner_text() and p.get_by_role('link',name='Abrir chamado humano').count()==1);p.get_by_role('button',name='Nova conversa').click();tid=int(p.url.rsplit('/',1)[-1]);p.locator('[name=body]').fill('Como configurar meu servidor de jogos?');p.locator('[name=consent]').check();p.get_by_role('button',name='Enviar para a IA').click();check('Mensagem aparece na fila','Aguardando resposta' in p.locator('body').inner_text());answer=fixture('answer',tid);check('Worker responde com modelo configurado',answer['status']=='done');expect(p.locator('[data-ai-answer]')).to_contain_text('Resposta simulada',timeout=15000);check('Atualização automática segura sem executar HTML',not p.evaluate('window.ai_fixture_xss') and '<script>' in p.locator('[data-ai-answer]').inner_text())
 p.set_viewport_size({'width':390,'height':900});check('Chat sem overflow móvel',p.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));p.set_viewport_size({'width':1440,'height':1000});p.get_by_role('button',name='Excluir esta conversa do painel').click();check('Exclusão disponível ao titular','Conversa removida deste painel' in p.locator('body').inner_text());check('Conversa excluída indisponível',ctx.request.get(BASE+f'/painel/chat/{tid}/estado').status==404);check('Cliente não acessa chave/configuração ADM',ctx.request.get(BASE+'/admin/integracoes/ollama').status==403)
 check('Sem erros JavaScript',not errors);b.close()
report={'results':results,'javascript_errors':errors,'external_providers':'Simulados; catálogo via CLI controller + Http::fake, lifecycle e inferência via workers interceptados'};(ROOT/'docs/BROWSER-PTERO-AI-RESULTS.json').write_text(json.dumps(report,indent=2,ensure_ascii=False));sys.exit(any(not x['passed']for x in results))
