"""Alpha.3 support checks against a LOCAL fictional demo; no live external systems."""
import json,os,re,subprocess,uuid,sys
from pathlib import Path
from urllib.parse import urlparse
import ipaddress
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];BASE=os.environ.get('LAGOS_TEST_URL','http://127.0.0.1:8080');F=json.loads((ROOT/'.cache/demo.json').read_text());suffix=uuid.uuid4().hex[:8]
assert urlparse(BASE).scheme=='http' and (urlparse(BASE).hostname=='localhost' or ipaddress.ip_address(urlparse(BASE).hostname).is_loopback), 'Fixtures are local-only'
(ROOT/'docs/BROWSER-SUPPORT-RESULTS.json').unlink(missing_ok=True)
operators=json.loads(subprocess.run(['php','tests/support-fixture.php'],cwd=ROOT,env=dict(os.environ,LAGOS_TEST_MODE='1'),capture_output=True,text=True,check=True).stdout)
results=[];errors=[];assets=[]
def check(label,ok):
 results.append({'test':label,'passed':bool(ok)});print(('PASS 'if ok else'FAIL ')+label)
with sync_playwright()as pw:
 b=pw.chromium.launch(headless=True,args=['--no-sandbox']);ctx=b.new_context(viewport={'width':1440,'height':1000},extra_http_headers={'X-Forwarded-For':'192.0.2.43'});p=ctx.new_page();p.on('pageerror',lambda e:errors.append(str(e)));p.on('response',lambda r:assets.append(r.url)if r.status>=400 and r.request.resource_type in('script','stylesheet','image')else None)
 def go(path):
  r=p.goto(BASE+path);check('HTTP '+path,r.status==200);return r
 def login(email,password):
  go('/entrar');p.locator('[name=email]').fill(email);p.locator('[name=password]').fill(password);p.get_by_role('button',name='Entrar',exact=True).click();p.wait_for_url('**/painel')
 def logout():p.locator('form[action$="/sair"] button').click()
 login(F['client'],F['password']);go('/painel/suporte');form=p.locator('form[action$="/painel/suporte"]');subject='Suporte Alpha3 '+suffix;form.locator('[name=subject]').fill(subject);form.locator('[name=priority]').select_option('urgent');form.locator('[name=body]').fill('Ajuda com diagnóstico privado.');filename='diagnostico-'+('a'*130)+'.txt';content=('Registro privado '+suffix).encode();form.locator('[name="attachments[]"]').set_input_files({'name':filename,'mimeType':'text/plain','buffer':content});form.get_by_role('button',name='Enviar ticket',exact=True).click();card=p.locator('.card[id^=ticket-]').filter(has_text=subject);tid=int(card.get_attribute('id').split('-')[1]);check('Chamado urgente com meta de duas horas','Meta de resposta: 2 horas' in card.inner_text());download_url=card.get_by_role('link',name='Baixar '+filename,exact=True).get_attribute('href')
 with p.expect_download()as d:card.get_by_role('link',name='Baixar '+filename,exact=True).click()
 check('Download preserva conteúdo',Path(d.value.path()).read_bytes()==content)
 response=ctx.request.get(download_url);check('Anexo não pode executar no navegador',response.headers.get('content-type')=='application/octet-stream' and 'sandbox' in response.headers.get('content-security-policy',''))
 p.set_viewport_size({'width':390,'height':900});check('Suporte móvel e nome longo sem overflow',p.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));p.set_viewport_size({'width':1440,'height':1000});card.get_by_role('link',name='Histórico completo',exact=True).click();check('Histórico individual',p.url.endswith('/painel/suporte/'+str(tid)));p.get_by_role('button',name='Encerrar chamado',exact=True).click();check('Fechamento remove formulário de resposta',not p.get_by_role('button',name='Enviar resposta',exact=True).count());p.get_by_role('button',name='Reabrir chamado',exact=True).click();check('Reabertura restaura atendimento',p.get_by_role('button',name='Enviar resposta',exact=True).count()==1);logout()
 login(F['admin'],F['password']);go('/admin/suporte/'+str(tid));triage=p.locator('form[action$="/triagem"]');triage.locator('[name=assigned_to]').select_option(str(operators['writer']['id']));triage.get_by_role('button',name='Salvar triagem',exact=True).click();check('Atribuição pela interface','Triagem atualizada' in p.locator('body').inner_text());form=p.locator(f'form[action$="/admin/suporte/{tid}"]');form.locator('[name=body]').fill('SEGREDO-INTERNO-'+suffix);form.locator('[name=internal]').check();form.locator('[name="attachments[]"]').set_input_files({'name':'interno.txt','mimeType':'text/plain','buffer':b'Privado da equipe'});form.get_by_role('button',name='Enviar resposta',exact=True).click();check('Nota interna identificada','Nota interna registrada' in p.locator('body').inner_text());internal_url=p.get_by_role('link',name='Baixar interno.txt',exact=True).get_attribute('href');check('Equipe pode baixar nota',ctx.request.get(internal_url).body()==b'Privado da equipe');form=p.locator(f'form[action$="/admin/suporte/{tid}"]');form.locator('[name=body]').fill('Resposta pública '+suffix);form.get_by_role('button',name='Enviar resposta',exact=True).click();check('Resposta pública limpa prazo','Resposta prevista:' not in p.locator('body').inner_text());p.set_viewport_size({'width':390,'height':900});check('Atendimento administrativo móvel sem overflow',p.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));p.set_viewport_size({'width':1440,'height':1000});logout()
 login(operators['writer']['email'],operators['writer']['password']);go('/admin/suporte?mine=1&priority=urgent');check('Filtro por responsável encontra ticket',subject in p.locator('body').inner_text());logout()
 login(operators['viewer']['email'],operators['viewer']['password']);go('/admin/suporte/'+str(tid));check('Somente leitura vê notas sem formulários',('SEGREDO-INTERNO-'+suffix)in p.locator('body').inner_text() and not p.get_by_role('button',name='Enviar resposta',exact=True).count());csrf=p.locator('meta[name=csrf-token]').get_attribute('content');check('RBAC impede alteração por POST',ctx.request.post(BASE+f'/admin/suporte/{tid}/triagem',form={'_token':csrf,'priority':'low'}).status==403);logout()
 login(operators['outsider']['email'],operators['outsider']['password']);check('Outro cliente não lê chamado',p.goto(BASE+'/painel/suporte/'+str(tid)).status==404);check('Outro cliente não baixa anexo',ctx.request.get(download_url).status==404);go('/painel');logout()
 # Fresh browser login would share the explicit auth rate budget; reuse the legitimate client only once more.
 login(F['client'],F['password']);go('/painel/suporte/'+str(tid));body=p.locator('body').inner_text();check('Cliente vê resposta mas nunca nota interna',('Resposta pública '+suffix)in body and ('SEGREDO-INTERNO-'+suffix)not in body and 'interno.txt' not in body);aid=internal_url.rsplit('/',1)[-1];check('Dono também não baixa anexo interno',ctx.request.get(BASE+'/painel/anexos/'+aid).status==404);check('Administração continua restrita',ctx.request.get(internal_url).status==403);check('Sem exceções JavaScript',not errors);check('Sem assets ausentes',not assets);b.close()
report={'results':results,'js_errors':errors,'failed_assets':assets};(ROOT/'docs/BROWSER-SUPPORT-RESULTS.json').write_text(json.dumps(report,indent=2,ensure_ascii=False));print(f'{sum(x["passed"]for x in results)} passed / {sum(not x["passed"]for x in results)} failed');sys.exit(any(not x['passed']for x in results))
