"""LOCAL demo: web-search harness and site configuration. All provider calls use CLI Http::fake."""
import json,os,subprocess,uuid,sys,ipaddress,base64
from pathlib import Path
from urllib.parse import urlparse
from playwright.sync_api import sync_playwright,expect
ROOT=Path(__file__).resolve().parents[1];BASE=os.environ.get('LAGOS_TEST_URL','http://127.0.0.1:8080');F=json.loads((ROOT/'.cache/demo.json').read_text());suffix=uuid.uuid4().hex[:8]
assert urlparse(BASE).scheme=='http' and (urlparse(BASE).hostname=='localhost' or ipaddress.ip_address(urlparse(BASE).hostname).is_loopback)
(ROOT/'docs/BROWSER-WEB-SITE-RESULTS.json').unlink(missing_ok=True)
results=[];errors=[]
def check(label,ok):results.append({'test':label,'passed':bool(ok)});print(('PASS 'if ok else'FAIL ')+label)
def fixture(*args):return json.loads(subprocess.run(['php','tests/ptero-ai-fixture.php',*map(str,args)],cwd=ROOT,env=dict(os.environ,LAGOS_TEST_MODE='1'),capture_output=True,text=True,check=True).stdout)
with sync_playwright()as pw:
 b=pw.chromium.launch(headless=True,args=['--no-sandbox']);ctx=b.new_context(viewport={'width':1440,'height':1000},extra_http_headers={'X-Forwarded-For':'192.0.2.48'});p=ctx.new_page();p.on('pageerror',lambda e:errors.append(str(e)))
 def go(path):r=p.goto(BASE+path);check('HTTP '+path,r.status==200);return r
 def login(email):
  go('/entrar');p.locator('[name=email]').fill(email);p.locator('[name=password]').fill(F['password']);p.get_by_role('button',name='Entrar',exact=True).click();p.wait_for_url('**/painel')
 def logout():p.locator('form[action$="/sair"] button').click()
 login(F['admin']);go('/admin/configuracoes');p.locator('[name=name]').fill('Painel configurado '+suffix);p.locator('[name=url]').fill(BASE);p.locator('[name=support_email]').fill('suporte@example.test');p.locator('[name=registration_enabled]').uncheck();p.locator('[name=mailer]').select_option('log');p.locator('[name=logo]').set_input_files({'name':'logo.png','mimeType':'image/png','buffer':base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=')});p.get_by_role('button',name='Salvar configurações do site').click();check('Nome, cadastro e logo salvos pelo ADM','Configuração salva' in p.locator('body').inner_text() and 'Painel configurado '+suffix in p.title());check('Logo é recurso local com MIME seguro',ctx.request.get(BASE+'/marca/logo').headers.get('content-type')=='image/png')
 p.set_viewport_size({'width':390,'height':900});check('Configurações sem overflow móvel',p.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));p.set_viewport_size({'width':1440,'height':1000});p.get_by_role('button',name='Enviar teste para meu e-mail').click();check('Teste de e-mail com modo log é explícito','Modo log grava localmente' in p.locator('body').inner_text())
 guest=b.new_context();r=guest.request.get(BASE+'/registrar');check('Cadastro desativado também no servidor',r.status==403);gp=guest.new_page();gp.goto(BASE+'/loja');check('Marca e contato aparecem na loja, sem convite de cadastro','Painel configurado '+suffix in gp.title() and gp.get_by_role('link',name='suporte@example.test',exact=True).count()==1 and not gp.get_by_role('link',name='Criar conta',exact=True).count());guest.close()
 # Restore baseline demo settings for subsequent suites/manual exploration.
 p.locator('[name=name]').fill('LagosPanel');p.locator('[name=registration_enabled]').check();p.locator('[name=remove_logo]').check();p.locator('[name=support_email]').fill('');p.locator('[name=mailer]').select_option('inherit');p.get_by_role('button',name='Salvar configurações do site').click();check('Configuração reversível sem trocar assets','Configuração salva' in p.locator('body').inner_text());go('/admin/integracoes/ollama');p.locator('[name=web_enabled]').check();p.locator('[name=web_token]').fill('fake-web-cloud-key-'+suffix);p.locator('[name=active]').check();p.locator('[name=ack]').check();p.get_by_role('button',name='Salvar configuração Ollama').click();check('Pesquisa habilitada com chave oculta','Configuração salva' in p.locator('body').inner_text() and 'fake-web-cloud-key-'+suffix not in p.content());logout()
 login(F['client']);go('/painel/chat');p.get_by_role('link',name='Nova conversa',exact=True).click();check('Pesquisa tem consulta e consentimento próprios',p.locator('[name=web_query]').count()==1 and p.locator('[name=web_consent]').count()==1);p.locator('[name=body]').fill('Quero documentação atual para pesquisar.');p.locator('.chat-web-options>summary').click();p.locator('[name=web_requested]').check();p.locator('[name=web_query]').fill('Documentação pública Ollama web search');p.locator('[name=web_consent]').check();p.locator('[name=consent]').check();p.locator('[data-chat-send]').click();expect(p.locator('[data-ai-turn]')).to_have_count(1);tid=int(p.url.rsplit('/',1)[-1]);result=fixture('answer',tid);check('Harness pesquisa e gera resposta em fila',result['status']=='done');expect(p.locator('[data-ai-sources] a')).to_have_count(1,timeout=15000);link=p.locator('[data-ai-sources] a');check('Fontes da busca aparecem com URL e proteção de referência',link.get_attribute('href')=='https://docs.ollama.com/capabilities/web-search' and 'noreferrer' in link.get_attribute('rel'));check('HTML do modelo continua inerte',not p.evaluate('window.ai_fixture_xss'));p.reload();check('Fontes persistem sem JavaScript de atualização',p.locator('[data-ai-sources] a').count()==1);r=ctx.request.get(BASE+f'/painel/chat/{tid}/estado');payload=r.json();check('Estado não expõe chave nem trechos brutos','fake-web-cloud-key' not in r.text() and 'content' not in payload['turns'][0]['sources'][0]);p.locator('[data-chat-tools]>summary').click();p.once('dialog',lambda d:d.accept());p.get_by_role('button',name='Excluir conversa',exact=True).click();check('Exclusão remove fontes da conversa',ctx.request.get(BASE+f'/painel/chat/{tid}/estado').status==404);check('Sem erros JavaScript',not errors);b.close()
(ROOT/'docs/BROWSER-WEB-SITE-RESULTS.json').write_text(json.dumps({'results':results,'javascript_errors':errors,'external_network':'simulated search and inference; log mail'},indent=2,ensure_ascii=False));sys.exit(any(not x['passed']for x in results))
