@extends('layouts.panel')
@section('title','Suporte com Ollama')
@section('content')
<div class="card"><h2>Conexão e modelo de IA</h2><p>Configure Ollama Cloud ou um servidor compatível com a API nativa Ollama. A chave permanece no servidor, criptografada. O catálogo será consultado com esta chave; aparecer na lista não garante cota ou permissão de geração.</p><p class="muted">A IA recebe somente o texto da conversa e um histórico limitado, não acessa faturas, senhas, anexos ou comandos. O provedor poderá armazenar o conteúdo conforme sua política. Confira privacidade e custos antes de habilitar.</p><p>Estado: <strong>{{ $setting?->active?'Habilitado':'Desabilitado' }}</strong> · Chave: {{ $setting?->token?'Configurada (oculta)':'Não configurada' }}</p></div>
@if(auth()->user()->hasPermission('integrations.manage'))
<div class="card"><form method="post" action="{{ route('admin.connectors.ai.save') }}">@csrf<input type="hidden" name="version" value="{{ $setting?->version??0 }}"><div class="field"><label>Origem da API (sem /api)</label><input name="endpoint" type="text" maxlength="255" value="{{ old('endpoint',$setting?->endpoint??'https://ollama.com') }}" required></div><div class="field"><label>Chave API — deixe vazio para manter</label><input name="token" type="password" autocomplete="new-password" maxlength="2000"></div><label><input type="checkbox" name="clear_token" value="1"> Remover chave (servidor próprio sem autenticação)</label><div class="field"><label>Modelo disponível no catálogo consultado</label><select name="model"><option value="">Consulte os modelos e selecione</option>@foreach($setting?->models??[] as $model)<option value="{{ $model }}" @selected($setting?->model===$model)>{{ $model }}</option>@endforeach</select></div><p class="muted">Alterar URL ou chave limpa o catálogo e a seleção. Salve desativado, consulte os modelos, escolha e habilite. Configuração nova invalida solicitações ainda pendentes.</p><div class="card"><h3>Pesquisa web para qualquer modelo</h3><p>Ferramenta da aplicação: consulta até cinco resultados na API de pesquisa Ollama Cloud. Não exige tool calling do modelo e não dá navegação irrestrita.</p><label class="check-line"><input type="checkbox" name="web_enabled" value="1" @checked($setting?->web_enabled)> Permitir pesquisas solicitadas pelo cliente</label><div class="field"><label>Chave Ollama Cloud de pesquisa (vazio mantém)</label><input type="password" name="web_token" maxlength="2000" autocomplete="new-password"></div><label><input type="checkbox" name="clear_web_token" value="1"> Remover chave de pesquisa separada</label><p class="muted">Se a origem principal for https://ollama.com, pode reutilizar a chave principal. Chaves de servidores locais/customizados nunca são repassadas automaticamente ao serviço cloud. A consulta escrita pelo cliente será enviada à pesquisa.</p></div><label class="check-line"><input type="checkbox" name="active" value="1" @checked($setting?->active)> Habilitar chat para clientes</label><label class="check-line"><input type="checkbox" name="ack" value="1"> Autorizo o envio das conversas ao provedor configurado; conferi política de dados, custos e disponibilidade.</label><button class="btn btn-primary">Salvar configuração Ollama</button></form></div>
@if($setting)<div class="card"><form method="post" action="{{ route('admin.connectors.ai.models') }}">@csrf<button class="btn btn-ghost">Consultar modelos com a chave salva</button></form><p class="muted">Última consulta: {{ $setting->models_checked_at?->format('d/m/Y H:i')??'Ainda não realizada' }}. Esta ação faz uma consulta real à URL configurada; modelos não são baixados ou instalados.</p></div>@endif
@endif
<div class="card"><p>Cloud: <code>https://ollama.com</code>. Servidor próprio: HTTPS com certificado válido. HTTP de loopback exige autorização explícita na configuração de implantação e só acessa o servidor onde roda o LagosPanel, não o computador do cliente.</p><a href="{{ route('admin.connectors') }}">Voltar às integrações</a></div>
@endsection
