@extends('layouts.panel')
@section('title','Assistente de IA')
@section('content')
@php $draft=$errors->any()&&old('_ai_form')==='settings'; @endphp
<div class="settings-heading"><div><span class="eyebrow">CONEXÃO, MODELO E FUNCIONAMENTO</span><h2>Seu assistente, sem mistério.</h2><p>Use Ollama Cloud ou uma API nativa Ollama. Conectar o modelo e manter a fila funcionando são etapas diferentes.</p></div><span class="settings-hero-icon">{!! panel_icon('zap',28) !!}</span></div>
<div class="ai-health-grid">
<div class="card"><small>CHAT DOS CLIENTES</small><strong>{{ $setting?->active?'Habilitado':'Desabilitado' }}</strong><span>{{ $setting?->model??'Nenhum modelo selecionado' }}</span></div>
<div class="card"><small>CHAVE DA API</small><strong>{{ $setting?->token?'Chave salva ✓':'Sem chave salva' }}</strong><span>{{ $setting?->token?'Criptografada. O campo vazio não apaga a chave.':'Cloud exige uma chave. Servidor próprio pode não exigir.' }}</span></div>
<div class="card"><small>WORKER DA FILA</small><strong>{{ $diagnostics['worker_recent']?'Sinal recente ✓':'Sem sinal recente' }}</strong><span>{{ $diagnostics['worker_seen_at']?'Último sinal: '.$diagnostics['worker_seen_at'].' UTC':'Não confirmado desde esta atualização' }}</span></div>
<div class="card"><small>GERAÇÃO DE TESTE</small><strong>{{ $diagnostics['probe_status']==='ok'?'Resposta recebida ✓':($diagnostics['probe_status']?'Teste falhou':'Ainda não testada') }}</strong><span>{{ $diagnostics['queued'] }} na fila · {{ $diagnostics['processing'] }} em processamento</span></div>
</div>
@if(!$diagnostics['worker_recent'])<div class="settings-callout">{!! panel_icon('alert',24) !!}<p><strong>O chat precisa de um worker permanente.</strong> Sem ele, a mensagem entra na fila, mas não chega ao modelo. Conexão: <code>database</code>, fila <code>{{ $diagnostics['queue_name'] }}</code>. Execute <code>php artisan lagos:ai-status</code> no servidor e confira <code>docs/IA-FOTO-E-OPERACAO.md</code>. Um worker anterior à atualização também precisa ser reiniciado para emitir esse sinal.</p></div>@endif
@if($diagnostics['paused'])<div class="alert alert-warning">A aplicação está em manutenção ou há uma pausa de atualização. Não remova a pausa sem conferir a operação em andamento.</div>@endif
@if($diagnostics['last_failure'])<div class="alert alert-warning"><strong>Última falha de uma resposta:</strong> {{ $diagnostics['last_failure'] }}</div>@endif
@if($diagnostics['probe_status']&&$diagnostics['probe_status']!=='ok')<div class="alert alert-warning"><strong>Teste desta configuração:</strong> {{ \App\Services\AiFailure::message($diagnostics['probe_status']) }}</div>@endif
@if(auth()->user()->hasPermission('integrations.manage'))
<div class="card"><form method="post" action="{{ route('admin.connectors.ai.save') }}">@csrf<input type="hidden" name="_ai_form" value="settings"><input type="hidden" name="version" value="{{ $draft?old('version'):($setting?->version??0) }}"><h3>1. Conectar a API</h3><p class="muted">A chave salva nunca é enviada novamente ao navegador. Para trocar, digite uma nova chave. Para manter, deixe o campo vazio.</p><div class="form-grid"><div class="field"><label for="ai-endpoint">Origem da API (sem /api)</label><input id="ai-endpoint" name="endpoint" type="text" maxlength="255" value="{{ old('endpoint',$setting?->endpoint??'https://ollama.com') }}" required><small>Ollama Cloud: https://ollama.com</small></div><div class="field"><label for="ai-token">Chave API / token</label><div class="secret-entry"><input id="ai-token" name="token" type="password" autocomplete="new-password" maxlength="2000" placeholder="{{ $setting?->token?'Chave já salva — vazio mantém':'Cole a chave da API aqui' }}"><button type="button" data-secret-toggle="ai-token" aria-label="Mostrar somente o token digitado" aria-pressed="false">Mostrar digitado</button></div><label class="check-line"><input type="checkbox" name="clear_token" value="1"> Remover chave salva</label></div></div>
<h3>2. Selecionar o modelo</h3><div class="field"><label for="ai-model">Modelo do catálogo consultado</label><select id="ai-model" name="model"><option value="">Consulte os modelos e selecione</option>@foreach($setting?->models??[] as $model)<option value="{{ $model }}" @selected(($draft?old('model'):$setting?->model)===$model)>{{ $model }}</option>@endforeach</select></div><p class="muted">Na primeira conexão: salve desativado, consulte o catálogo abaixo, selecione um modelo e salve novamente. Alterar URL ou chave exige nova consulta. Modelos listados podem não estar disponíveis para geração na sua conta.</p>
<details class="ai-web-settings"><summary>{!! panel_icon('globe',17) !!} Pesquisa web opcional</summary><p>A aplicação pesquisa no Ollama Cloud e envia os trechos ao modelo. Não exige tool calling nem dá navegação irrestrita.</p><label class="check-line"><input type="hidden" name="web_enabled" value="0"><input type="checkbox" name="web_enabled" value="1" @checked($draft?old('web_enabled'):$setting?->web_enabled)> Permitir pesquisas solicitadas pelo cliente</label><div class="field"><label for="ai-web-token">Chave Ollama Cloud para pesquisa</label><div class="secret-entry"><input id="ai-web-token" type="password" name="web_token" maxlength="2000" autocomplete="new-password" placeholder="{{ $setting?->web_token?'Chave separada salva — vazio mantém':'Opcional quando usa a chave principal do Ollama Cloud' }}"><button type="button" data-secret-toggle="ai-web-token" aria-label="Mostrar somente a chave de pesquisa digitada" aria-pressed="false">Mostrar digitado</button></div></div><label class="check-line"><input type="checkbox" name="clear_web_token" value="1"> Remover chave de pesquisa separada</label><p class="muted">A chave principal só é reutilizada quando a origem é https://ollama.com. Chaves de outros servidores não são enviadas ao Cloud.</p></details>
<h3>3. Disponibilizar aos clientes</h3><label class="check-line"><input type="hidden" name="active" value="0"><input type="checkbox" name="active" value="1" @checked($draft?old('active'):$setting?->active)> Habilitar chat para clientes</label><label class="check-line"><input type="checkbox" name="ack" value="1"> Autorizo o envio das conversas ao provedor; conferi privacidade, custos e disponibilidade.</label><p class="muted">A IA recebe apenas o texto e parte do histórico. Não acessa contas nem executa comandos. Alterar a configuração invalida solicitações pendentes.</p><button class="btn btn-primary">Salvar configuração Ollama</button></form></div>
@if($setting)<div class="ai-test-grid"><div class="card"><h3>Consultar catálogo</h3><p>Confere conexão e lista modelos. Não testa a geração de respostas nem instala modelos.</p><form method="post" action="{{ route('admin.connectors.ai.models') }}">@csrf<button class="btn btn-ghost">Consultar modelos com a chave salva</button></form><small>Última consulta: {{ $setting->models_checked_at?->format('d/m/Y H:i')??'Não realizada' }}.</small></div>
@if(auth()->user()->is_admin)<div class="card"><h3>Testar uma resposta</h3><p>Envia apenas a frase fixa “Responda apenas OK”, diretamente ao modelo selecionado, sem dados de clientes. Pode consumir cota do provedor e levar até 45 segundos.</p><form method="post" action="{{ route('admin.connectors.ai.probe') }}">@csrf @include('admin.webhook-confirm')<label class="check-line"><input type="checkbox" name="ack" value="1" required> Autorizo esta chamada real de teste.</label><button class="btn btn-primary">Testar geração com a chave salva</button></form><small>Não substitui a verificação do worker. Configure o timeout PHP-FPM/proxy para suportar a duração do teste.</small></div>@endif</div>@endif
@endif
<div class="card"><h3>Se a IA não responder</h3><ol><li>Confirme chave e modelo, depois teste a geração.</li><li>Se a geração falhar, confira o motivo acima: autenticação, permissão, modelo, limite ou conexão.</li><li>Se a geração funcionar e o chat ficar na fila, confira o worker database no servidor.</li><li>Servidor próprio exige HTTPS válido; HTTP de loopback precisa de autorização de implantação.</li></ol><a href="{{ route('admin.settings.index') }}">Voltar às configurações</a></div>
<script src="{{ panel_asset('assets/ai-settings.js') }}" defer></script>
@endsection
