@extends('layouts.panel')
@section('title','Integrações')
@section('content')
<div class="card"><a class="btn btn-ghost" href="{{ route('admin.webhooks.index') }}">Webhooks de saída e entregas</a></div>
<p><a class="btn btn-ghost" href="{{ route('admin.connectors.ai') }}">Configurar chat Ollama e modelos</a></p>
<div class="card"><h3>Integrações de provisionamento</h3><p class="muted">Conector JSON próprio e driver nativo cPanel/WHM API 1. Credenciais são criptografadas. Testes locais simulados não substituem homologação no provedor.</p><p class="muted">aaPanel: chave API, whitelist de IP e HTTPS na porta configurada. Gerencia sites, não cria contas isoladas de cliente; não fornece login administrativo.</p><p class="muted">DirectAdmin: Login Key e usuário, HTTPS 2222/443. Plesk: secret key XML API, HTTPS 8443/443; assinaturas sob proprietário existente, sem compartilhar login administrativo.</p><p>Chamadas nativas: <strong>{{ config('lagos.native_provisioning')?'Liberadas pela configuração local':'Bloqueadas pela configuração local' }}</strong>. Configure somente endpoints e servidores autorizados.</p>
@if(auth()->user()->hasPermission('integrations.manage'))
<form method="post" action="{{ route('admin.connectors.create') }}">@csrf<div class="form-grid"><div class="field"><label>Nome</label><input name="name" type="text" required maxlength="120"></div><div class="field"><label>Driver</label><select name="driver"><option value="directadmin">DirectAdmin — contas</option><option value="plesk">Plesk — assinaturas gerenciadas</option><option value="json">JSON próprio via HTTPS</option><option value="cpanel">cPanel / WHM API 1 — homologação pendente</option><option value="pterodactyl">Pterodactyl — Application API</option><option value="aapanel">aaPanel — sites gerenciados, homologação pendente</option></select></div></div><div class="field"><label>URL HTTPS base</label><input name="endpoint" type="text" placeholder="https://whm.exemplo.com:2087" required maxlength="255"></div><div class="field"><label>Token (não será exibido após salvar)</label><input name="token" type="password" required minlength="16" maxlength="2000" autocomplete="new-password"></div><details><summary>Campos nativos: prefixo para ambos; usuário para WHM/DirectAdmin; URL de cliente só para WHM</summary><div class="form-grid"><div class="field"><label>Usuário WHM ou DirectAdmin (administrador/revendedor)</label><input name="whm_username" type="text" maxlength="32"></div><div class="field"><label>Prefixo exclusivo deste painel (2 letras minúsculas)</label><input name="account_prefix" type="text" maxlength="2" placeholder="lg"></div><div class="field"><label>URL HTTPS do cPanel para o cliente</label><input name="client_url" type="text" placeholder="https://host.exemplo.com:2083" maxlength="255"></div></div><p class="muted">No WHM, use origem sem caminho, porta 2087 ou 443; no cPanel, 2083 ou 443. O prefixo deve ser exclusivo entre instalações que compartilham este servidor.</p></details><label class="check-line"><input type="checkbox" name="active" value="1"> Habilitar integração</label><label class="check-line"><input type="checkbox" name="ack_native" value="1"> Para drivers nativos, autorizo operações reais no servidor configurado e farei homologação isolada.</label><button class="btn btn-primary">Cadastrar integração</button></form>
@endif</div>
@foreach($connectors as $c)
@if($c->driver==='plesk' && auth()->user()->hasPermission('customers.view'))<p><a class="btn btn-ghost" href="{{ route('admin.connectors.plesk-customers',$c) }}">Clientes Plesk — {{ $c->name }}</a></p>@endif
@if($c->driver==='pterodactyl' && auth()->user()->hasPermission('customers.view'))<p><a class="btn btn-ghost" href="{{ route('admin.connectors.accounts',$c) }}">Contas Pterodactyl — {{ $c->name }}</a></p>@endif
<div class="card"><h3>{{ $c->name }}</h3><p>{{ $c->endpoint }} · {{ ['cpanel'=>'cPanel / WHM API 1','aapanel'=>'aaPanel / sites gerenciados','pterodactyl'=>'Pterodactyl','directadmin'=>'DirectAdmin','plesk'=>'Plesk / assinaturas gerenciadas'][$c->driver]??'JSON próprio' }}</p><span class="badge badge-{{ $c->active?'active':'pending' }}">{{ $c->active?'Habilitada':'Desabilitada' }}</span>
@if(auth()->user()->hasPermission('integrations.manage'))<form method="post" action="{{ route('admin.connectors.update',$c) }}">@csrf<div class="field"><label>Novo token (vazio mantém o atual)</label><input type="password" name="token" minlength="16" maxlength="2000" autocomplete="new-password"></div><label class="check-line"><input type="checkbox" name="active" value="1" @checked($c->active)> Habilitar integração</label>@if(in_array($c->driver,['cpanel','aapanel','pterodactyl','directadmin','plesk'],true))<label class="check-line"><input type="checkbox" name="ack_native" value="1"> Autorizo chamadas ao provedor configurado.</label>@endif<button class="btn btn-ghost btn-sm">Salvar integração</button></form>@endif</div>@endforeach
@endsection
