@extends('layouts.panel')
@section('title','Operações')
@section('content')
<div class="card"><p class="muted">Falhas ou respostas incertas exigem conciliação no provedor. Não há repetição automática. Para cPanel, a consulta compara conta, domínio, proprietário, pacote e e-mail com o contrato.</p><div class="table-wrap"><table><thead><tr><th>Operação</th><th>Serviço</th><th>Ação</th><th>Estado</th><th>Detalhes</th></tr></thead><tbody>@forelse($operations as $o)<tr><td>#{{ $o->id }}</td><td>{{ $o->service->name }}</td><td>{{ $o->action }}</td><td>{{ status_label($o->status) }}</td><td>{{ $o->error??'—' }}</td></tr>@empty<tr><td colspan="5">Nenhuma operação remota registrada.</td></tr>@endforelse</tbody></table></div></div>
@foreach($operations as $o)@if(in_array($o->service->connector?->driver,['cpanel','aapanel','pterodactyl'],true) && in_array($o->status,['review','processing','reconciling'],true))<div class="card"><h3>Conciliação provedor #{{ $o->id }}</h3><p>{{ $o->service->native_username??($o->service->provisioning['external_id']??'Serviço #'.$o->service_id) }} · {{ $o->action }} · {{ $o->status }}</p>@if($o->inspection)<p>Última consulta: {{ $o->inspection['status'] }} · {{ $o->inspection['checked_at'] }}</p>@endif
@if(auth()->user()->hasPermission('operations.manage') && auth()->user()->hasPermission('services.manage'))
@if($o->status==='review')<form method="post" action="{{ route('admin.operations.reconcile',$o) }}">@csrf<div class="field"><label>Decisão após consultar novamente o provedor</label><select name="decision"><option value="inspect">Somente consultar (não muda serviço nem repete)</option><option value="confirm">Confirmar resultado já observado no provedor</option><option value="retry">Autorizar uma nova tentativa pela fila</option></select></div><div class="field"><label>Justificativa / evidência conferida no servidor</label><textarea name="note" required minlength="10" maxlength="500"></textarea></div><label class="check-line"><input type="checkbox" name="ack" value="1" required> Conferi o vínculo e, antes de confirmar ou repetir, verifiquei que não existe operação ainda em execução no provedor. Sei que encerrar remove dados.</label><button class="btn btn-ghost btn-sm">Consultar e aplicar decisão</button></form>
@elseif($o->updated_at->lt(now()->subMinutes(5)))<form method="post" action="{{ route('admin.operations.interrupted',$o) }}">@csrf<div class="field"><label>Justificativa da interrupção</label><input name="note" required minlength="10" maxlength="500"></div><label><input type="checkbox" name="ack" value="1" required> Conferi a interrupção. Apenas mover para revisão, sem repetir chamadas.</label><button class="btn btn-ghost btn-sm">Marcar para revisão</button></form>@else<p>Aguarde a operação. Interrupções só podem ser marcadas após cinco minutos.</p>@endif
@endif</div>@endif
@endforeach
{{ $operations->links('layouts.pagination') }}
@endsection
