@extends('layouts.panel')
@section('title', 'Relatórios financeiros')
@section('content')
<div class="card"><form method="get" action="{{ route('admin.reports') }}"><div class="form-grid"><div class="field"><label>De (AAAA-MM-DD)</label><input name="from" type="text" value="{{ $range['from'] }}" required></div><div class="field"><label>Até (AAAA-MM-DD)</label><input name="to" type="text" value="{{ $range['to'] }}" required></div></div><button class="btn btn-primary btn-sm">Filtrar período</button> <a class="btn btn-ghost btn-sm" href="{{ route('admin.reports.export',$range) }}">Exportar faturas CSV</a></form></div>
<div class="stats-grid">
@foreach([[brl($summary['gross']),'Recebimentos externos'],[brl($summary['net']),'Receita líquida do ledger'],[brl($summary['refunds']),'Reembolsos'],[brl($summary['chargebacks']),'Chargebacks'],[brl($summary['open']),'Contas em aberto'],[brl($balances),'Saldo dos clientes']] as [$amount,$label])<div class="stat-card"><div><strong>{{ $amount }}</strong><span>{{ $label }}</span></div></div>@endforeach
</div>
<div class="card"><h2>Contas a receber por idade</h2><p class="muted">Valores ainda em aberto, separados por vencimento. Use esta visão para priorizar cobrança e suspensão com transparência.</p><div class="stats-grid">@foreach([['a_vencer','A vencer'],['1_7_dias','1–7 dias vencida'],['8_30_dias','8–30 dias vencida'],['mais_30_dias','Mais de 30 dias']] as [$key,$label])<div class="stat-card"><div><strong>{{ brl($summary['aging'][$key] ?? 0) }}</strong><span>{{ $label }}</span></div></div>@endforeach</div></div>
<div class="card"><p class="muted">Recebimentos externos excluem pagamentos internos com saldo para evitar dupla contagem. A receita líquida é o ledger de pagamentos menos reembolsos e chargebacks; não representa lucro nem apuração fiscal.</p><div class="table-wrap"><table><thead><tr><th>Data</th><th>Fatura</th><th>Meio</th><th>Valor</th><th>Status</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->created_at->format('d/m/Y H:i') }}</td><td>#{{ $payment->invoice_id }}</td><td>{{ $payment->gateway }}</td><td>{{ brl($payment->amount_minor) }}</td><td>{{ status_label($payment->status ?? 'captured') }}</td></tr>@empty<tr><td colspan="5">Nenhum recebimento no período.</td></tr>@endforelse</tbody></table></div></div>{{ $payments->links('layouts.pagination') }}
@endsection
