@extends('layouts.panel')
@section('title',$section==='email'?'Configurações — e-mail':'Configurações — geral e identidade')
@section('content')
@include('admin.configuration.nav')
<div class="card"><h2>{{ $section==='email'?'E-mail e notificações':'Geral e identidade' }}</h2><p>{{ $section==='email'?'Configure o transportador e envie um teste. O modo log não envia mensagens externas.':'Altere a identidade sem trocar o tema. Alterar URL não configura DNS ou certificado.' }}</p></div>
@if(auth()->user()->hasPermission('settings.manage'))
<div class="card"><form method="post" enctype="multipart/form-data" action="{{ route($section==='email'?'admin.settings.email.save':'admin.settings.general.save') }}">@csrf<input type="hidden" name="version" value="{{ $setting?->version??0 }}">
@if($section==='general')
<div class="form-grid"><div class="field"><label>Nome do site</label><input name="name" maxlength="80" required value="{{ old('name',$setting?->name??config('app.name')) }}"></div><div class="field"><label>URL principal HTTPS</label><input name="url" maxlength="255" required value="{{ old('url',$setting?->url??config('app.url')) }}"></div><div class="field"><label>E-mail público de suporte</label><input name="support_email" type="email" value="{{ old('support_email',$setting?->support_email) }}"></div><div class="field"><label>Logo PNG/JPEG/WebP (até 200 KiB, 1600px)</label><input type="file" name="logo" accept=".png,.jpg,.jpeg,.webp"></div></div><label class="check-line"><input type="checkbox" name="remove_logo" value="1"> Restaurar logo original</label><label class="check-line"><input type="checkbox" name="registration_enabled" value="1" @checked(old('registration_enabled',$setting?->registration_enabled??true))> Permitir novos cadastros públicos</label>
@else
<div class="form-grid"><div class="field"><label>Modo</label><select name="mailer">@foreach(['inherit'=>'Manter configuração do servidor','log'=>'Log local (não entrega e-mail)','smtp'=>'SMTP'] as $key=>$label)<option value="{{ $key }}" @selected(old('mailer',$setting?->mailer??'inherit')===$key)>{{ $label }}</option>@endforeach</select></div><div class="field"><label>Remetente</label><input type="email" name="mail_from_address" value="{{ old('mail_from_address',$setting?->mail_from_address) }}"></div><div class="field"><label>Host SMTP</label><input name="smtp_host" value="{{ old('smtp_host',$setting?->smtp_host) }}"></div><div class="field"><label>Porta</label><input type="number" min="1" max="65535" name="smtp_port" value="{{ old('smtp_port',$setting?->smtp_port??587) }}" required></div><div class="field"><label>Segurança</label><select name="smtp_scheme"><option value="smtp" @selected(old('smtp_scheme',$setting?->smtp_scheme??'smtp')==='smtp')>STARTTLS obrigatório</option><option value="smtps" @selected(old('smtp_scheme',$setting?->smtp_scheme)==='smtps')>TLS implícito</option></select></div><div class="field"><label>Usuário SMTP</label><input name="smtp_username" value="{{ old('smtp_username',$setting?->smtp_username) }}"></div><div class="field"><label>Senha SMTP — vazio mantém</label><input type="password" name="smtp_password" autocomplete="new-password" maxlength="2000"></div></div><label class="check-line"><input type="checkbox" name="clear_smtp_password" value="1"> Remover senha SMTP salva</label>
@endif
<button class="btn btn-primary">Salvar {{ $section==='email'?'configuração de e-mail':'identidade do site' }}</button></form></div>
@if($section==='email')<div class="card"><form method="post" action="{{ route('admin.settings.mail') }}">@csrf<button class="btn btn-ghost">Enviar teste para meu e-mail</button></form><p>Modo atual: {{ config('mail.default') }}. Um teste SMTP aceito não comprova entrega na caixa de entrada; mantenha o worker de notificações ativo.</p></div>@endif
@else<div class="card"><p>Permissão somente de leitura.</p><p>Nome: {{ $setting?->name??config('app.name') }}</p><p>URL: {{ $setting?->url??config('app.url') }}</p>@if($section==='email')<p>Modo de e-mail: {{ $setting?->mailer??'inherit' }}</p>@endif</div>@endif
@endsection
