@extends('layouts.panel')
@section('title','Configurações do site')
@section('content')
<div class="card"><h2>Identidade e operação</h2><p class="muted">Configure o site sem substituir o tema. Alterar URL não cria DNS/certificado. Configuração de e-mail controla notificações e links de recuperação: restrinja esta permissão.</p></div>
@if(auth()->user()->hasPermission('settings.manage'))
<div class="card"><form method="post" enctype="multipart/form-data" action="{{ route('admin.settings.save') }}">@csrf<input type="hidden" name="version" value="{{ $setting?->version??0 }}"><div class="form-grid"><div class="field"><label>Nome do site</label><input name="name" maxlength="80" required value="{{ old('name',$setting?->name??config('app.name')) }}"></div><div class="field"><label>URL principal HTTPS</label><input name="url" maxlength="255" required value="{{ old('url',$setting?->url??config('app.url')) }}"></div><div class="field"><label>E-mail público de suporte</label><input name="support_email" type="email" value="{{ old('support_email',$setting?->support_email) }}"></div><div class="field"><label>Logo PNG/JPEG/WebP (até 200 KiB, 1600px)</label><input type="file" name="logo" accept=".png,.jpg,.jpeg,.webp"></div></div><label class="check-line"><input type="checkbox" name="remove_logo" value="1"> Restaurar logo original</label><label class="check-line"><input type="checkbox" name="registration_enabled" value="1" @checked($setting?->registration_enabled??true)> Permitir novos cadastros públicos</label>
<h3>E-mail</h3><div class="form-grid"><div class="field"><label>Modo</label><select name="mailer">@foreach(['inherit'=>'Manter configuração do servidor','log'=>'Log local (não entrega e-mail)','smtp'=>'SMTP'] as $key=>$label)<option value="{{ $key }}" @selected(($setting?->mailer??'inherit')===$key)>{{ $label }}</option>@endforeach</select></div><div class="field"><label>Remetente</label><input type="email" name="mail_from_address" value="{{ $setting?->mail_from_address }}"></div><div class="field"><label>Host SMTP</label><input name="smtp_host" value="{{ $setting?->smtp_host }}"></div><div class="field"><label>Porta</label><input type="number" min="1" max="65535" name="smtp_port" value="{{ $setting?->smtp_port??587 }}" required></div><div class="field"><label>Segurança</label><select name="smtp_scheme"><option value="smtp" @selected(($setting?->smtp_scheme??'smtp')==='smtp')>STARTTLS obrigatório</option><option value="smtps" @selected($setting?->smtp_scheme==='smtps')>TLS implícito</option></select></div><div class="field"><label>Usuário SMTP</label><input name="smtp_username" value="{{ $setting?->smtp_username }}"></div><div class="field"><label>Senha SMTP — vazio mantém</label><input type="password" name="smtp_password" autocomplete="new-password" maxlength="2000"></div></div><label class="check-line"><input type="checkbox" name="clear_smtp_password" value="1"> Remover senha SMTP salva</label><button class="btn btn-primary">Salvar configurações do site</button></form></div>
<div class="card"><form method="post" action="{{ route('admin.settings.mail') }}">@csrf<button class="btn btn-ghost">Enviar teste para meu e-mail</button></form></div>
@else<div class="card"><p>Nome: {{ $setting?->name??config('app.name') }}</p><p>URL: {{ $setting?->url??config('app.url') }}</p><p>Permissão somente de leitura.</p></div>@endif
@endsection
