@extends('layouts.panel')
@section('title','Webhooks de saída')
@section('content')
<div class="card"><h2>Webhooks de saída</h2><p>Envio global: {{ config('lagos.outgoing_webhooks')?'habilitado':'desabilitado (OUTGOING_WEBHOOKS_ENABLED=false)' }}. Exige cron a cada minuto e worker de fila. Eventos ficam no outbox mesmo com o envio global pausado.</p><p>Somente IDs e tipo do recurso são enviados; notas, senhas, e-mails e contexto da auditoria não são transmitidos. Destinatários devem deduplicar pelo ID do evento. Desativar um destino cancela suas pendências quando processadas, mas não recolhe requisições já em trânsito.</p>
@forelse($endpoints as $endpoint)<details class="card"><summary>{{ $endpoint->name }} · {{ $endpoint->active?'Ativo':'Desativado' }}</summary><p style="overflow-wrap:anywhere">{{ $endpoint->url }}</p><p>{{ implode(', ',$endpoint->events) }}</p>@if(auth()->user()->hasPermission('integrations.manage'))<form method="post" action="{{ route('admin.webhooks.state',$endpoint) }}">@csrf<input type="hidden" name="active" value="{{ $endpoint->active?0:1 }}">@include('admin.webhook-confirm')<button class="btn btn-ghost">{{ $endpoint->active?'Desativar destino':'Reativar destino' }}</button></form>@endif</details>
@empty<p>Nenhum destino cadastrado.</p>@endforelse
{{ $endpoints->links('layouts.pagination') }}</div>
<div class="card"><h3>Entregas</h3><div class="table-wrap"><table><thead><tr><th>Evento</th><th>Destino</th><th>Estado</th><th>Tentativas</th></tr></thead><tbody>@forelse($deliveries as $delivery)<tr><td><a href="{{ route('admin.webhooks.show',$delivery) }}">#{{ $delivery->id }} {{ $delivery->event_type }}</a></td><td>{{ $delivery->endpoint->name }}</td><td>{{ $delivery->status }}</td><td>{{ $delivery->attempts }}/{{ $delivery->max_attempts }}</td></tr>@empty<tr><td colspan="4">Nenhuma entrega registrada.</td></tr>@endforelse</tbody></table></div>{{ $deliveries->links('layouts.pagination') }}</div>
@if(auth()->user()->hasPermission('integrations.manage'))<div class="card"><h3>Novo destino</h3><p>URL e chave ficam imutáveis. Para rotacionar ou mudar URL, desative o destino antigo e crie outro. Não há replay retroativo automático.</p><form method="post" action="{{ route('admin.webhooks.create') }}">@csrf<div class="field"><label>Nome</label><input name="name" maxlength="100" required></div><div class="field"><label>URL HTTPS pública (porta 443, sem query)</label><input name="url" type="url" maxlength="1000" required></div><div class="field"><label>Eventos</label>@foreach($events as $event)<label><input type="checkbox" name="events[]" value="{{ $event }}"> {{ $event }}</label>@endforeach</div>@include('admin.webhook-confirm')<label><input type="checkbox" name="ack" value="1" required> Autorizo o envio dos eventos selecionados a este destino sob meu controle.</label><button class="btn btn-primary">Criar destino e mostrar chave</button></form></div>@endif
@endsection
