<?php

use App\Http\Controllers\AdminConfigurationController;
use App\Http\Controllers\AiChatController;
use App\Http\Controllers\AiSettingsController;
use App\Http\Controllers\ApiAccessController;
use App\Http\Controllers\CannedReplyController;
use App\Http\Controllers\CommerceController;
use App\Http\Controllers\InvoiceDocumentController;
use App\Http\Controllers\KnowledgeController;
use App\Http\Controllers\NativeProvisioningController;
use App\Http\Controllers\OperationalSettingsController;
use App\Http\Controllers\PanelUpdateController;
use App\Http\Controllers\PterodactylAccountController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SiteSettingsController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\TeamController;
use Illuminate\Support\Facades\Route;

Route::get('/marca/logo', [SiteSettingsController::class, 'logo'])->name('brand.logo');
Route::get('/conhecimento', [KnowledgeController::class, 'index'])->name('knowledge.index');
Route::get('/conhecimento/{slug}', [KnowledgeController::class, 'show'])->name('knowledge.show');
Route::middleware(['auth', 'auth.session', 'verified'])->group(function () {
    Route::get('/painel/chat', [AiChatController::class, 'index'])->name('ai.index');
    Route::post('/painel/chat', [AiChatController::class, 'create'])->middleware('throttle:5,1,lagos-ai-new')->name('ai.create');
    Route::get('/painel/chat/{thread}', [AiChatController::class, 'index'])->name('ai.show');
    Route::post('/painel/chat/{thread}', [AiChatController::class, 'send'])->middleware('throttle:6,1,lagos-ai-send')->name('ai.send');
    Route::get('/painel/chat/{thread}/estado', [AiChatController::class, 'state'])->middleware('throttle:60,1,lagos-ai-state')->name('ai.state');
    Route::post('/painel/chat/{thread}/renomear', [AiChatController::class, 'rename'])->middleware('throttle:15,1,lagos-ai-rename')->name('ai.rename');
    Route::post('/painel/chat/{thread}/excluir', [AiChatController::class, 'delete'])->name('ai.delete');
    Route::get('/painel/faturas/{invoice}/pdf', [InvoiceDocumentController::class, 'download'])->middleware('throttle:10,1,lagos-invoice-pdf')->name('invoices.pdf');
    Route::post('/painel/servicos/{service}/energia', [NativeProvisioningController::class, 'power'])->middleware('throttle:5,1,lagos-ptero-power')->name('services.power');
    Route::post('/painel/servicos/{service}/acesso-cpanel', [NativeProvisioningController::class, 'session'])->middleware('throttle:3,1,lagos-native-session')->name('services.session');
    Route::post('/painel/servicos/{service}/acesso-plesk', [NativeProvisioningController::class, 'pleskSession'])->middleware('throttle:3,1,lagos-native-session')->name('services.plesk-session');
    Route::post('/painel/servicos/{service}/acesso-inicial', [NativeProvisioningController::class, 'credentials'])->middleware('throttle:5,1,lagos-native-credentials')->name('services.credentials');
    Route::get('/painel/suporte/{ticket}', [SupportController::class, 'thread'])->name('tickets.show');
    Route::get('/painel/anexos/{attachment}', [SupportController::class, 'download'])->middleware('throttle:30,1,lagos-support-download')->name('tickets.download');
    Route::post('/painel/suporte/{ticket}/estado', [SupportController::class, 'state'])->middleware('throttle:10,1,lagos-ticket-state')->name('tickets.state');
    Route::get('/painel/carrinho', [CommerceController::class, 'cart'])->name('cart.index');
    Route::post('/painel/carrinho', [CommerceController::class, 'add'])->middleware('throttle:30,1,lagos-cart-add')->name('cart.add');
    Route::post('/painel/carrinho/{item}/quantidade', [CommerceController::class, 'update'])->name('cart.update');
    Route::post('/painel/carrinho/{item}/remover', [CommerceController::class, 'remove'])->name('cart.remove');
    Route::post('/painel/carrinho/finalizar', [CommerceController::class, 'checkout'])->middleware('throttle:20,1,lagos-cart-checkout')->name('cart.checkout');
    Route::post('/painel/faturas/{invoice}/cancelar', [CommerceController::class, 'cancel'])->name('invoices.cancel');
    Route::get('/painel/api', [ApiAccessController::class, 'index'])->name('api.index');
    Route::post('/painel/api', [ApiAccessController::class, 'create'])->middleware('throttle:5,1,lagos-api-token-create')->name('api.create');
    Route::post('/painel/api/{token}/revogar', [ApiAccessController::class, 'revoke'])->name('api.revoke');
    Route::prefix('admin')->name('admin.')->middleware('admin')->group(function () {
        Route::get('/faturas/{invoice}/pdf', [InvoiceDocumentController::class, 'download'])->middleware('throttle:30,1,lagos-staff-invoice-pdf')->name('invoices.pdf');
        Route::get('/suporte/modelos', [CannedReplyController::class, 'index'])->name('tickets.templates');
        Route::get('/suporte/modelos/{template}/editar', [CannedReplyController::class, 'index'])->name('tickets.templates.edit');
        Route::post('/suporte/modelos', [CannedReplyController::class, 'save'])->name('tickets.templates.create');
        Route::post('/suporte/modelos/{template}', [CannedReplyController::class, 'save'])->name('tickets.templates.update');
        Route::get('/suporte/{ticket}/modelos/{template}', [CannedReplyController::class, 'content'])->name('tickets.templates.content');
        Route::get('/configuracoes/recursos-disponiveis', [OperationalSettingsController::class, 'coverage'])->name('settings.coverage');
        Route::get('/configuracoes/operacao/{section}', [OperationalSettingsController::class, 'index'])->name('settings.operation');
        Route::post('/configuracoes/operacao/{section}', [OperationalSettingsController::class, 'save'])->middleware('throttle:10,1,lagos-operation-settings')->name('settings.operation.save');
        Route::get('/configuracoes', [AdminConfigurationController::class, 'index'])->name('settings.index');
        Route::get('/configuracoes/atualizacoes', [PanelUpdateController::class, 'index'])->name('settings.updates');
        Route::post('/configuracoes/atualizacoes/conferir', [PanelUpdateController::class, 'check'])->middleware('throttle:3,1,lagos-update-check')->name('settings.updates.check');
        Route::post('/configuracoes/atualizacoes/{update}/aprovar', [PanelUpdateController::class, 'approve'])->middleware('throttle:3,1,lagos-update-approve')->name('settings.updates.approve');
        Route::post('/configuracoes/atualizacoes/{update}/cancelar', [PanelUpdateController::class, 'cancel'])->name('settings.updates.cancel');
        Route::get('/configuracoes/atualizacoes/{update}/estado', [PanelUpdateController::class, 'state'])->middleware('throttle:30,1,lagos-update-state')->name('settings.updates.state');
        Route::get('/configuracoes/geral', [SiteSettingsController::class, 'index'])->defaults('section', 'general')->name('settings.general');
        Route::post('/configuracoes/geral', [SiteSettingsController::class, 'save'])->defaults('section', 'general')->name('settings.general.save');
        Route::get('/configuracoes/email', [SiteSettingsController::class, 'index'])->defaults('section', 'email')->name('settings.email');
        Route::post('/configuracoes/email', [SiteSettingsController::class, 'save'])->defaults('section', 'email')->name('settings.email.save');
        Route::get('/configuracoes/seguranca', [AdminConfigurationController::class, 'security'])->name('settings.security');
        Route::post('/configuracoes/seguranca', [AdminConfigurationController::class, 'saveSecurity'])->middleware('throttle:5,1,lagos-admin-security')->name('settings.security.save');
        Route::get('/configuracoes/ambiente', [AdminConfigurationController::class, 'environment'])->name('settings.environment');
        Route::post('/configuracoes', [SiteSettingsController::class, 'save'])->name('settings.save');
        Route::post('/configuracoes/email-teste', [SiteSettingsController::class, 'testMail'])->middleware('throttle:3,1,lagos-mail-test')->name('settings.mail');
        Route::get('/integracoes/ollama', [AiSettingsController::class, 'index'])->name('connectors.ai');
        Route::post('/integracoes/ollama', [AiSettingsController::class, 'save'])->name('connectors.ai.save');
        Route::post('/integracoes/ollama/modelos', [AiSettingsController::class, 'models'])->middleware('throttle:5,1,lagos-ai-models')->name('connectors.ai.models');
        Route::get('/integracoes/{connector}/clientes-plesk', [NativeProvisioningController::class, 'pleskCustomers'])->name('connectors.plesk-customers');
        Route::get('/integracoes/{connector}/contas', [PterodactylAccountController::class, 'index'])->name('connectors.accounts');
        Route::post('/integracoes/{connector}/contas/criar-remota', [PterodactylAccountController::class, 'provision'])->middleware('throttle:6,1,lagos-ptero-users')->name('connectors.accounts.provision');
        Route::post('/integracoes/{connector}/contas/solicitacoes/{accountRequest}/conferir', [PterodactylAccountController::class, 'inspect'])->middleware('throttle:10,1,lagos-ptero-users-check')->name('connectors.accounts.inspect');
        Route::post('/integracoes/{connector}/contas', [PterodactylAccountController::class, 'create'])->name('connectors.accounts.create');
        Route::post('/integracoes/{connector}', [NativeProvisioningController::class, 'connector'])->name('connectors.update');
        Route::post('/operacoes/{operation}/preparar-conta', [NativeProvisioningController::class, 'prepareAccount'])->middleware('throttle:5,1,lagos-ptero-prepare')->name('operations.prepare-account');
        Route::post('/operacoes/{operation}/conciliar', [NativeProvisioningController::class, 'inspect'])->middleware('throttle:10,1,lagos-native-review')->name('operations.reconcile');
        Route::post('/operacoes/{operation}/interrompida', [NativeProvisioningController::class, 'interrupted'])->name('operations.interrupted');
        Route::get('/suporte/{ticket}', [SupportController::class, 'thread'])->whereNumber('ticket')->name('tickets.show');
        Route::get('/suporte/anexos/{attachment}', [SupportController::class, 'download'])->middleware('throttle:60,1,lagos-staff-download')->name('tickets.download');
        Route::post('/suporte/{ticket}/triagem', [SupportController::class, 'triage'])->name('tickets.triage');
        Route::get('/produtos/{product}/opcoes', [CommerceController::class, 'options'])->name('products.options');
        Route::post('/produtos/{product}/opcoes', [CommerceController::class, 'createOption'])->name('products.options.create');
        Route::post('/produtos/{product}/opcoes/{option}/valores', [CommerceController::class, 'createValue'])->name('products.values.create');
        Route::post('/produtos/{product}/valores/{value}/alternar', [CommerceController::class, 'toggleValue'])->name('products.values.toggle');
        Route::get('/conciliacao', [ReportController::class, 'reviews'])->name('reviews');
        Route::post('/conciliacao/{review}', [ReportController::class, 'resolve'])->name('reviews.resolve');
        Route::get('/relatorios', [ReportController::class, 'index'])->name('reports');
        Route::get('/relatorios/faturas.csv', [ReportController::class, 'export'])->name('reports.export');
        Route::get('/equipe', [TeamController::class, 'index'])->name('team.index');
        Route::post('/equipe/funcoes', [TeamController::class, 'create'])->name('team.create');
        Route::post('/equipe/usuarios/{user}', [TeamController::class, 'assign'])->name('team.assign');
        Route::get('/conhecimento', [KnowledgeController::class, 'admin'])->name('knowledge');
        Route::get('/conhecimento/{article}/editar', [KnowledgeController::class, 'admin'])->name('knowledge.edit');
        Route::post('/conhecimento', [KnowledgeController::class, 'save'])->name('knowledge.create');
        Route::post('/conhecimento/{article}', [KnowledgeController::class, 'save'])->name('knowledge.update');
    });
});
