@extends($admin?'layouts.panel':'layouts.public')
@section('title', 'Avisos e status')
@section('content')
<div class="card"><h2>Avisos e status</h2><p>{{ $active? $active.' incidente(s) ou manutenção(ões) com impacto informado.':'Nenhum incidente com impacto informado no momento.' }}</p><p class="muted">Informações publicadas pela equipe. Esta página não é monitoramento automático nem medição de disponibilidade.</p>
@forelse($bulletins as $bulletin)<p><a href="{{ route($admin?'admin.bulletins.show':'bulletins.show',$bulletin) }}">{{ $bulletin->title }}</a> · {{ ['announcement'=>'Aviso','incident'=>'Incidente','maintenance'=>'Manutenção'][$bulletin->kind] }} · {{ ['open'=>'Aberto','monitoring'=>'Em observação','resolved'=>'Resolvido'][$bulletin->state] }}@if($admin) · {{ !$bulletin->published?'Não publicado':($bulletin->published_at->isFuture()?'Agendado':'Publicado') }}@endif</p>
@empty<p>Nenhuma publicação disponível.</p>@endforelse
{{ $bulletins->links('layouts.pagination') }}</div>
@if($admin && auth()->user()->hasPermission('bulletins.manage'))<div class="card"><h3>Nova publicação</h3><form method="post" action="{{ route('admin.bulletins.create') }}">@csrf<div class="field"><label>Título</label><input name="title" maxlength="180" required value="{{ old('title') }}"></div><div class="form-grid"><div class="field"><label>Tipo</label><select name="kind"><option value="announcement">Aviso</option><option value="incident">Incidente</option><option value="maintenance">Manutenção</option></select></div><div class="field"><label>Impacto (incidente/manutenção)</label><select name="severity"><option value="information">Informativo</option><option value="degraded">Degradação</option><option value="outage">Indisponibilidade</option></select></div><div class="field"><label>Publicar a partir de ({{ config('app.timezone') }}; vazio = agora)</label><input type="datetime-local" name="published_at" value="{{ old('published_at') }}"></div></div><div class="field"><label>Descrição e serviços afetados</label><textarea name="body" rows="8" maxlength="20000" required>{{ old('body') }}</textarea></div><label><input type="checkbox" name="published" value="1"> Disponibilizar publicamente na data definida</label><button class="btn btn-primary">Criar publicação</button></form></div>@endif
@endsection
