@extends('layouts.panel')
@section('title', 'Downloads')
@section('content')
<div class="card"><h2>Downloads</h2><p>Arquivos da equipe. Materiais vinculados a um produto exigem serviço ativo desse produto. Arquivos gerais são exclusivos de clientes com e-mail verificado.</p>
@forelse($assets as $asset)<details class="card"><summary>{{ $asset->title }}</summary><p style="white-space:pre-wrap;overflow-wrap:anywhere">{{ $asset->description }}</p><p>{{ $asset->product?->name??'Material geral' }} · {{ number_format($asset->size/1024,1,',','.') }} KiB</p><p style="overflow-wrap:anywhere">SHA-256: {{ $asset->sha256 }}</p><a class="btn btn-primary btn-sm" href="{{ route($admin?'admin.downloads.fetch':'downloads.fetch',$asset) }}">Baixar arquivo</a>
@if($admin && auth()->user()->hasPermission('downloads.manage'))<form method="post" action="{{ route('admin.downloads.state',$asset) }}">@csrf<input type="hidden" name="active" value="{{ $asset->active?'0':'1' }}"><button class="btn btn-ghost btn-sm">{{ $asset->active?'Desativar':'Disponibilizar' }}</button></form>@endif
</details>@empty<p>Nenhum download disponível.</p>@endforelse
{{ $assets->links('layouts.pagination') }}</div>
@if($admin && auth()->user()->hasPermission('downloads.manage'))<div class="card"><h3>Adicionar arquivo</h3><p>Até 10 MiB: PDF, ZIP, TXT, GZ ou TAR. Não há antivírus; publique apenas material confiável e verificado. Não envie credenciais, backups de clientes ou dados pessoais.</p><form method="post" enctype="multipart/form-data" action="{{ route('admin.downloads.create') }}">@csrf<div class="field"><label>Título</label><input name="title" maxlength="180" required value="{{ old('title') }}"></div><div class="field"><label>Descrição</label><textarea name="description" rows="5" maxlength="10000" required>{{ old('description') }}</textarea></div><div class="field"><label>ID do produto (vazio = todos os clientes verificados)</label><input name="product_id" type="number" min="1" value="{{ old('product_id') }}"></div><div class="field"><label>Arquivo privado</label><input type="file" name="file" accept=".pdf,.zip,.txt,.gz,.tar" required></div><label><input type="checkbox" name="active" value="1"> Disponibilizar para clientes autorizados</label><button class="btn btn-primary">Salvar arquivo</button></form></div>@endif
@endsection
