@extends('layouts.panel')
@section('title','Assistente de IA')
@section('body-class','chat-page')
@section('content')
<link rel="stylesheet" href="{{ panel_asset('assets/chat.css') }}">
<section class="chat-app" data-ai-chat data-state-url="{{ $thread?route('ai.state',$thread):'' }}" data-new-url="{{ route('ai.create') }}" data-rename-url="{{ $thread?route('ai.rename',$thread):'' }}" data-delete-url="{{ $thread?route('ai.delete',$thread):'' }}" data-chat-index="{{ route('ai.index') }}">
<aside class="chat-history" id="chat-history"><div class="chat-history-heading"><span>{!! panel_icon('ticket',19) !!} Suas conversas</span><button class="icon-btn chat-history-close" type="button" aria-label="Fechar histórico" data-history-toggle>{!! panel_icon('x',18) !!}</button></div><a class="chat-new" href="{{ route('ai.index') }}">{!! panel_icon('plus',19) !!} Nova conversa</a><span class="chat-history-label">RECENTES</span><nav aria-label="Histórico de conversas" data-chat-history-list>@forelse($threads as $item)<a class="chat-history-item {{ $thread?->id===$item->id?'is-active':'' }}" href="{{ route('ai.show',$item) }}" data-thread-id="{{ $item->id }}"><span>{!! panel_icon('ticket',16) !!}</span><div><strong>{{ $item->displayTitle() }}</strong><small>{{ $item->updated_at->format('d/m · H:i') }}</small></div></a>@empty<p class="chat-history-empty" data-history-empty>Suas conversas aparecerão aqui.</p>@endforelse</nav><div class="chat-history-foot">{!! panel_icon('shield',17) !!}<span>Histórico exclusivo da sua conta.<br>Até 20 conversas.</span></div></aside>
<div class="chat-main"><header class="chat-header"><button type="button" class="icon-btn chat-history-mobile" aria-label="Abrir histórico de conversas" aria-controls="chat-history" aria-expanded="false" data-history-toggle>{!! panel_icon('menu',20) !!}</button><span class="chat-brand-icon">{!! panel_icon('zap',22) !!}</span><div><strong>Assistente {{ config('app.name') }}</strong><span><i class="{{ $available?'is-available':'' }}"></i>{{ $available?'Pronto para ajudar':'Indisponível no momento' }}</span></div><div class="chat-header-actions"><a class="chat-human" aria-label="Abrir chamado humano" href="{{ route('tickets.index') }}">{!! panel_icon('user',17) !!}<span>Suporte humano</span></a><details class="chat-tools" data-chat-tools @if(!$thread)hidden @endif><summary aria-label="Opções da conversa">•••</summary><div><form method="post" action="{{ $thread?route('ai.rename',$thread):'#' }}" data-rename-form>@csrf<label for="chat-title">Nome da conversa</label><input id="chat-title" name="title" maxlength="80" required value="{{ $thread?->displayTitle() }}"><button type="submit" class="btn btn-ghost btn-sm">Renomear</button></form><form method="post" action="{{ $thread?route('ai.delete',$thread):'#' }}" data-delete-form>@csrf<button type="submit" class="chat-delete">Excluir conversa</button></form><small>Excluir não apaga registros do provedor nem backups.</small></div></details></div></header>
<div class="chat-scroll" data-chat-scroll><div class="chat-welcome" data-chat-welcome @if($turns->isNotEmpty())hidden @endif><span class="chat-welcome-icon">{!! panel_icon('zap',34) !!}</span><span class="eyebrow">UMA CONVERSA, SEM COMPLICAÇÃO</span><h2>Olá, {{ Str::before(auth()->user()->name,' ') }}.<br>Como posso ajudar?</h2><p>Tire uma dúvida, entenda um conceito ou descubra por onde começar.</p><div class="chat-suggestions">@foreach([['globe','Domínio e hospedagem','Qual é a diferença entre domínio e hospedagem?'],['invoice','Entender uma fatura','Como posso conferir os detalhes da minha fatura no painel?'],['shield','Proteger minha conta','Como posso deixar minha conta mais segura?'],['ticket','Pedir ajuda à equipe','Que informações devo incluir ao abrir um chamado de suporte?']] as [$icon,$title,$question])<button type="button" data-chat-suggestion="{{ $question }}">{!! panel_icon($icon,21) !!}<span>{{ $title }}</span>{!! panel_icon('chevron',16) !!}</button>@endforeach</div></div>
<div class="chat-messages" data-chat-messages aria-label="Mensagens da conversa">
@foreach($turns as $turn)<article class="chat-turn" data-ai-turn="{{ $turn->id }}" data-state="{{ $turn->status }}"><div class="chat-message is-user"><div class="chat-message-body"><span class="chat-speaker">Você</span><div class="chat-bubble" data-ai-user>{{ $turn->user_text }}</div></div><span class="chat-avatar">{{ mb_strtoupper(mb_substr(auth()->user()->name,0,1)) }}</span></div><div class="chat-message is-assistant"><span class="chat-avatar">{!! panel_icon('zap',19) !!}</span><div class="chat-message-body"><span class="chat-speaker">Assistente</span><div class="chat-answer" data-ai-answer>{{ $turn->status==='done'?$turn->assistant_text:($turn->status==='failed'?\App\Services\AiFailure::message($turn->failure_code):($turn->status==='processing'?'Preparando sua resposta…':'Na fila. Aguardando o assistente…')) }}</div><div class="chat-pending" data-ai-pending @if(!in_array($turn->status,['queued','processing']))hidden @endif aria-label="Aguardando resposta"><i></i><i></i><i></i></div><div class="chat-sources" data-ai-sources>@if($turn->web_requested)<p data-web-notice>{{ ['searched'=>'Fontes encontradas — confira os links:','empty'=>'Pesquisa sem resultados públicos válidos.','failed'=>'Pesquisa indisponível; informações atuais não confirmadas.'][$turn->web_status]??'Pesquisa solicitada.' }}</p>@foreach($turn->web_sources??[] as $source)<a href="{{ $source['url'] }}" target="_blank" rel="noopener noreferrer nofollow">[{{ $source['id'] }}] {{ $source['title'] }}</a>@endforeach @endif</div><div class="chat-answer-actions"><button type="button" data-chat-copy @if($turn->status!=='done')hidden @endif>Copiar resposta</button><button type="button" data-chat-retry @if($turn->status!=='failed')hidden @endif>Usar esta mensagem novamente</button></div></div></div></article>@endforeach
</div></div>
<div class="chat-compose-area"><div class="chat-notice" data-ai-status role="status" aria-live="polite"></div>@if(!$available)<div class="chat-offline">A IA está indisponível. <a href="{{ route('tickets.index') }}">Fale com a equipe de suporte.</a></div>@else
<form method="post" action="{{ $thread?route('ai.send',$thread):route('ai.create') }}" data-chat-form>@csrf<input type="hidden" name="request_key" value="{{ (string)Str::uuid() }}">
@if(!$thread?->consented_at)<label class="chat-consent" data-chat-consent><input name="consent" type="checkbox" value="1" required> Autorizo enviar as mensagens e parte do histórico desta conversa ao provedor de IA. Não enviarei senhas nem dados sensíveis.</label>@endif
@if($webAvailable)<details class="chat-web-options"><summary>{!! panel_icon('globe',16) !!} Pesquisar na web <span>opcional</span></summary><div><label><input name="web_requested" type="checkbox" value="1"> Usar pesquisa nesta mensagem</label><div class="field"><label for="web-query">O que pesquisar? Apenas informações públicas.</label><input id="web-query" name="web_query" maxlength="400" placeholder="Ex.: documentação oficial de DNS"></div><label><input name="web_consent" type="checkbox" value="1"> Autorizo enviar essa consulta ao Ollama Cloud. O histórico não é enviado ao buscador.</label></div></details>@endif
<div class="chat-composer"><label class="sr-only" for="chat-message">Sua mensagem</label><textarea id="chat-message" name="body" placeholder="Digite sua mensagem…" rows="1" maxlength="2000" required></textarea><div class="chat-composer-bottom"><span><span data-chat-counter>0</span>/2.000 <span class="chat-key-hint">· Enter envia, Shift+Enter quebra linha</span></span><button type="submit" class="chat-send" aria-label="Enviar mensagem" @disabled($pending) data-chat-send>{!! panel_icon('send',19) !!}</button></div></div>
</form>@endif
<div class="chat-disclaimer"><span>A IA pode errar e não acessa sua conta nem executa ações.</span><details><summary>Privacidade e limites</summary><p>Até 2.000 caracteres por mensagem, 20 mensagens por conversa e {{ config('ai.daily_requests') }} solicitações diárias (UTC), incluindo falhas. O provedor recebe o texto e parte do histórico. Não envie segredos. Excluir conversas não restaura a cota. A pesquisa web envia somente a consulta explícita ao buscador; trechos encontrados são enviados ao modelo.</p></details></div><noscript><p>Sem JavaScript, use Enviar e recarregue a conversa para acompanhar a resposta.</p></noscript></div>
</div></section><script src="{{ panel_asset('assets/ai-chat.js') }}" defer></script>
@endsection
