@extends('layouts.panel')
@section('title','Chat de suporte · IA')
@section('content')
<div class="card"><div class="row-between"><h2>Assistente de IA</h2><a class="btn btn-ghost" href="{{ route('tickets.index') }}">Abrir chamado humano</a></div><p>As respostas são geradas por IA e podem estar erradas. O assistente não executa ações nem consulta sua conta. Não envie senhas, tokens, dados de pagamento ou outras informações sensíveis.</p><p class="muted">O texto e parte do histórico são enviados ao provedor Ollama configurado pela equipe. Limites: 2.000 caracteres por mensagem, 20 mensagens por conversa e {{ config('ai.daily_requests') }} solicitações diárias por conta (UTC), incluindo falhas. Excluir conversas não restaura a cota.</p>@if(!$available)<p class="alert alert-warning">Chat de IA indisponível. O atendimento humano continua disponível.</p>@endif
<form method="post" action="{{ route('ai.create') }}">@csrf<button class="btn btn-ghost">Nova conversa</button></form></div>
@if($thread)
<div class="card" data-ai-chat data-state-url="{{ route('ai.state',$thread) }}"><h3>Conversa #{{ $thread->id }}</h3>
@foreach($turns as $turn)<div class="card" data-ai-turn="{{ $turn->id }}" data-state="{{ $turn->status }}"><strong>Você</strong><p class="preserve" style="overflow-wrap:anywhere">{{ $turn->user_text }}</p><strong>Assistente de IA</strong><p class="preserve" style="overflow-wrap:anywhere" data-ai-answer>{{ $turn->status==='done'?$turn->assistant_text:($turn->status==='failed'?'Não foi possível concluir esta resposta. Nenhuma nova tentativa automática será feita. Abra um chamado ou envie uma nova mensagem.':'Aguardando resposta na fila…') }}</p><div data-ai-sources>@if($turn->web_requested)<p class="muted" data-web-notice>{{ ['searched'=>'Fontes encontradas pela pesquisa (trechos; confira os links):','empty'=>'Pesquisa sem resultados públicos válidos.','failed'=>'Pesquisa indisponível; informações atuais não foram confirmadas.'][$turn->web_status]??'Pesquisa solicitada; aguardando processamento.' }}</p>@foreach($turn->web_sources??[] as $source)<p><a href="{{ $source['url'] }}" target="_blank" rel="noopener noreferrer nofollow">[{{ $source['id'] }}] {{ $source['title'] }}</a></p>@endforeach @endif</div></div>@endforeach
<p data-ai-status role="status"></p><a class="btn btn-ghost btn-sm" href="{{ route('ai.show',$thread) }}">Atualizar conversa</a>
@if($available)<form method="post" action="{{ route('ai.send',$thread) }}">@csrf<input type="hidden" name="request_key" value="{{ (string)\Illuminate\Support\Str::uuid() }}"><div class="field"><label>Sua mensagem</label><textarea name="body" required maxlength="2000" rows="4"></textarea></div>@if($webAvailable)<div class="card"><label><input type="checkbox" name="web_requested" value="1"> Pesquisar informações atuais na web</label><div class="field"><label>Consulta pública de pesquisa (até 400 caracteres)</label><input type="text" name="web_query" maxlength="400" placeholder="Ex.: requisitos oficiais atuais do Pterodactyl"></div><label><input type="checkbox" name="web_consent" value="1"> Autorizo enviar essa consulta à pesquisa Ollama Cloud; não contém dados privados.</label><p class="muted">A consulta não envia seu histórico ao buscador. Os trechos encontrados são enviados ao modelo. Resultados podem estar errados ou desatualizados.</p></div>@endif
<label class="check-line"><input type="checkbox" name="consent" value="1" required> Entendo que esta conversa será enviada ao provedor de IA e não contém segredos.</label><button class="btn btn-primary">Enviar para a IA</button></form>@endif
<form method="post" action="{{ route('ai.delete',$thread) }}">@csrf<button class="btn btn-danger btn-sm">Excluir esta conversa do painel</button></form></div>
@endif
<div class="card"><h3>Suas conversas</h3>@forelse($threads as $item)<p><a href="{{ route('ai.show',$item) }}">Conversa #{{ $item->id }} · {{ $item->created_at->format('d/m/Y H:i') }}</a></p>@empty<p>Nenhuma conversa.</p>@endforelse</div>{{ $threads->links('layouts.pagination') }}
<script src="{{ asset('assets/ai-chat.js') }}" defer></script>
@endsection
