@extends('layouts.panel')
@section('title', 'Minha conta')
@section('content')
@include('client.avatar')
<div class="card"><h3>Dados da conta</h3><p>{{ auth()->user()->email }} · E-mail confirmado</p><form method="post" action="{{ route('profile.update') }}">@csrf<div class="field"><label>Nome</label><input type="text" name="name" value="{{ auth()->user()->name }}" required maxlength="100"></div><button class="btn btn-primary btn-sm">Salvar</button></form><p class="muted">Para redefinir sua senha, saia da conta e use a recuperação de acesso.</p></div><div class="card"><h3>Saldo: {{ brl(auth()->user()->balance_minor) }}</h3><p class="muted">A recarga só é creditada após confirmação do pagamento.</p><form method="post" action="{{ route('wallet.deposit') }}">@csrf<input type="hidden" name="request_key" value="{{ (string)Str::uuid() }}"><div class="field"><label>Valor da recarga (R$)</label><input type="text" name="amount" inputmode="decimal" placeholder="50,00" required></div><button class="btn btn-ghost btn-sm">Gerar fatura de recarga</button></form><div class="table-wrap"><table><thead><tr><th>Data</th><th>Movimento</th><th>Valor</th><th>Saldo após</th></tr></thead><tbody>@forelse($entries as $entry)<tr><td>{{ $entry->created_at->format('d/m/Y') }}</td><td>{{ $entry->description }}</td><td>{{ brl($entry->amount_minor) }}</td><td>{{ brl($entry->balance_after_minor) }}</td></tr>@empty<tr><td colspan="4">Nenhum movimento.</td></tr>@endforelse</tbody></table></div></div>{{ $entries->links('layouts.pagination') }}
<div class="card"><h3>Autenticação em duas etapas</h3>
@if(session('recovery_codes'))<div class="alert alert-warning">Guarde estes códigos em local seguro. Cada código só pode ser utilizado uma vez.<p class="preserve">{{ implode("\n",session('recovery_codes')) }}</p></div>@endif
@if(auth()->user()->totp_secret)<p>Proteção ativada.</p><form method="post" action="{{ route('two-factor.disable') }}">@csrf<div class="field"><label>Senha atual</label><input type="password" name="password" required autocomplete="current-password"></div><div class="field"><label>Código do autenticador</label><input type="text" name="code" required></div><button class="btn btn-danger btn-sm">Desativar duas etapas</button></form>
@elseif(session('totp_setup'))<p>Adicione manualmente esta chave no autenticador (TOTP, 6 dígitos, 30 segundos):</p><p class="preserve"><code>{{ session('totp_setup.secret') }}</code></p><form method="post" action="{{ route('two-factor.enable') }}">@csrf<div class="field"><label>Código do autenticador</label><input name="code" type="text" required autocomplete="one-time-code"></div><button class="btn btn-primary btn-sm">Confirmar ativação</button></form>
@else<p class="muted">Proteja a conta com um aplicativo autenticador.</p><form method="post" action="{{ route('two-factor.begin') }}">@csrf<div class="field"><label>Senha atual</label><input name="password" type="password" required autocomplete="current-password"></div><button class="btn btn-primary btn-sm">Configurar duas etapas</button></form>@endif</div>
@include('client.social-accounts')
@endsection
