@extends('layouts.panel')
@section('title', 'Meus serviços')
@section('content')
<div class="card">@include('client.service-table')</div>@foreach($services as $s)@if($s->status!=='cancelled')<details class="card"><summary>Gerenciar {{ $s->name }} #{{ $s->id }}</summary>@foreach($s->configuration??[] as $c)<p>{{ $c['name'] }}: {{ $c['label'] }}</p>@endforeach <p>{{ $s->connector_id?'Serviço com integração de provisionamento.':'Ativação e manutenção realizadas pela equipe.' }}</p>@if(in_array($s->provisioning['driver']??'', ['cpanel','directadmin','plesk'],true) && $s->status==='active')<p>Hospedagem: {{ $s->provisioning['domain'] }}</p><form method="post" action="{{ route('services.credentials',$s) }}">@csrf<div class="field"><label>Sua senha atual do LagosPanel</label><input type="password" name="password" required autocomplete="current-password"></div>@if(auth()->user()->totp_secret)<div class="field"><label>Código novo do autenticador</label><input type="text" name="code" inputmode="numeric" maxlength="6" required></div>@endif
@if(($s->provisioning['driver']??'')==='plesk' && ($s->provisioning['auto_customer']??false) && !empty($s->provisioning['customer_request_id']))<button class="btn btn-primary btn-sm" formaction="{{ route('services.plesk-session',$s) }}">Entrar no Plesk</button>@endif
@if(($s->provisioning['driver']??'')==='cpanel')<button class="btn btn-primary btn-sm" formaction="{{ route('services.session',$s) }}">Entrar no cPanel</button>@endif <button class="btn btn-ghost btn-sm">{{ ($s->provisioning['driver']??'')==='plesk'?'Ver acesso de publicação':'Ver acesso inicial' }}</button></form>@endif @if(($s->provisioning['driver']??'')==='plesk')<p style="overflow-wrap:anywhere">Assinatura Plesk gerenciada: {{ $s->provisioning['domain'] }}. Acesso administrativo não é compartilhado. Publique usando as credenciais FTP/FTPS da sua assinatura.</p>@endif @if(($s->provisioning['driver']??'')==='aapanel')<p style="overflow-wrap:anywhere">Site gerenciado: {{ $s->provisioning['domain'] }}. Publicação pela equipe; sem acesso administrativo aaPanel.</p>@endif @if(($s->provisioning['driver']??'')==='pterodactyl')<p>Servidor de jogos #{{ $s->remote_id??'aguardando instalação' }}. Use sua conta vinculada no painel de jogos.</p><a class="btn btn-ghost" href="{{ $s->provisioning['endpoint'] }}" rel="noreferrer">Abrir Pterodactyl</a>
@if($s->status==='active')<details><summary>Ligar, parar ou reiniciar</summary><p>Use a chave Client API da sua conta no Pterodactyl. Ela vale apenas nesta solicitação e não é armazenada. Não use chave Application API ou de administrador.</p><form method="post" action="{{ route('services.power',$s) }}">@csrf<input type="hidden" name="request_key" value="{{ (string) Str::uuid() }}"><div class="field"><label>Chave Client API</label><input type="password" name="token" autocomplete="off" required minlength="16" maxlength="2000"></div><div class="field"><label>Sua senha atual do LagosPanel</label><input type="password" name="password" autocomplete="current-password" required></div>@if(auth()->user()->totp_secret)<div class="field"><label>Código novo do autenticador</label><input name="code" inputmode="numeric" maxlength="6" required></div>@endif<div class="field"><label>Comando</label><select name="signal"><option value="start">Ligar</option><option value="stop">Parar</option><option value="restart">Reiniciar</option></select></div><label><input type="checkbox" name="ack" value="1" required> Entendo que parar ou reiniciar interrompe os jogadores. Em caso de dúvida, conferirei o estado no provedor antes de outro comando.</label><button class="btn btn-ghost">Enviar comando</button></form></details>@endif
@endif
@if($s->cancellation_requested_at)<p class="muted">Cancelamento solicitado em {{ $s->cancellation_requested_at->format('d/m/Y H:i') }}. Renovação automática desativada.</p>@else<form method="post" action="{{ route('services.cancel',$s) }}">@csrf<div class="field"><label>Motivo do cancelamento</label><textarea name="reason" required minlength="5" maxlength="2000"></textarea></div><button class="btn btn-danger btn-sm">Solicitar cancelamento</button></form>@endif</details>@endif
@endforeach
{{ $services->links('layouts.pagination') }}
@endsection
