@extends('layouts.panel')
@section('title',$section['title'])
@section('content')
@include('admin.configuration.nav')
@php $draft=$errors->any() && old('_operation_section')===$key; @endphp
<div class="settings-heading"><div><span class="eyebrow">CONFIGURAÇÕES DA OPERAÇÃO</span><h2>{{ $section['title'] }}</h2><p>{{ $section['description'] }}</p></div><span class="settings-hero-icon">{!! panel_icon($section['icon'],30) !!}</span></div>
<nav class="operation-tabs" aria-label="Configurações operacionais">@foreach(\App\Support\OperationalSettings::SECTIONS as $id=>$item)<a class="{{ $key===$id?'is-active':'' }}" href="{{ route('admin.settings.operation',$id) }}">{!! panel_icon($item['icon'],17) !!}{{ $item['title'] }}</a>@endforeach</nav>
@if($key==='automation')<div class="settings-callout">{!! panel_icon('clock',22) !!}<p><strong>Requer scheduler e fila ativos.</strong> O comando <code>php artisan lagos:maintenance</code> aplica as regras e é agendado a cada hora. Suspensão depende do conector e do provisionamento habilitados. Desativar não cancela operações já enfileiradas. Reduzir prazos pode afetar faturas vencidas na próxima execução.</p></div>@endif
@if($key==='payments')<div class="settings-callout">{!! panel_icon('shield',22) !!}<p><strong>Use credenciais de teste antes de habilitar pagamentos reais.</strong> O ambiente deve corresponder às credenciais e aos eventos enviados pelo gateway. Nunca troque o modo de produção no meio de uma conciliação.</p></div><div class="card"><h3>Retornos dos gateways</h3><p>Stripe: <code class="preserve">{{ url('/webhooks/stripe') }}</code></p><p>Mercado Pago: <code class="preserve">{{ url('/webhooks/mercadopago') }}</code></p><p class="muted">A confirmação ocorre no backend. O retorno do navegador não aprova uma fatura.</p></div>@endif
<div class="card"><form method="post" action="{{ route('admin.settings.operation.save',$key) }}">@csrf<input type="hidden" name="version" value="{{ $draft?old('version'):($setting?->version??0) }}"><fieldset @disabled(!auth()->user()->hasPermission('settings.manage'))><div class="operation-fields">
@foreach($section['fields'] as $field=>[$label,$path,$type,$min,$max])
<div class="field {{ $type==='textarea'?'operation-wide':'' }}">
@if($type==='boolean')<input type="hidden" name="values[{{ $field }}]" value="0"><label class="operation-toggle"><span>{{ $label }}</span><input type="checkbox" name="values[{{ $field }}]" value="1" @checked($draft?old('values.'.$field,config($path)):config($path))></label>
@else<label for="operation-{{ $field }}">{{ $label }}</label>
@if($type==='secret')<input id="operation-{{ $field }}" type="password" name="values[{{ $field }}]" maxlength="{{ $max }}" autocomplete="new-password" placeholder="{{ config($path)?'Credencial configurada — vazio mantém':'Informe a credencial' }}"><label class="check-line"><input type="checkbox" name="clear[{{ $field }}]" value="1"> Apagar a credencial efetiva (desative o gateway antes)</label><small>{{ config($path)?'Credencial salva. Deixar vazio mantém o valor atual.':'Nenhuma credencial configurada.' }}</small>
@elseif($type==='textarea')<textarea id="operation-{{ $field }}" name="values[{{ $field }}]" maxlength="{{ $max }}" rows="4">{{ $draft?old('values.'.$field,config($path)):config($path) }}</textarea>
@else<input id="operation-{{ $field }}" name="values[{{ $field }}]" type="{{ $type==='integer'?'number':'text' }}" value="{{ $draft?old('values.'.$field,config($path)):config($path) }}" @if($type==='integer')min="{{ $min }}" max="{{ $max }}" step="1"@else maxlength="{{ $max }}"@endif @required($min>0 || $type==='integer')>
@endif @endif
</div>
@endforeach
</div><div class="operation-confirm"><h3>Confirmar alteração</h3><p>Para salvar, informe sua senha de acesso abaixo e marque a confirmação. Isso não altera sua senha.</p><p>Estes valores substituem as opções correspondentes do ambiente, sem editar o arquivo .env.</p>@include('admin.webhook-confirm')<label class="check-line"><input type="checkbox" name="ack" value="1" required> Revisei os valores e entendo o efeito nas próximas operações.</label><button class="btn btn-primary">Salvar configurações</button></div></fieldset></form></div>
@if($key==='support')<div class="card"><h3>Outras opções de atendimento</h3><p>Os departamentos atuais são Suporte e Financeiro. Os limites por arquivo continuam em 2 MiB e 3 anexos por mensagem. Alterar a cota da conta não remove anexos existentes.</p>@if(auth()->user()->hasPermission('support.view'))<a class="btn btn-ghost" href="{{ route('admin.tickets.templates') }}">Respostas prontas</a>@endif</div>@endif
@endsection
