<!doctype html><html lang="pt-BR"><head>@include('layouts.head')</head><body class="lagos-panel-page"><div class="panel-shell"><aside class="sidebar" id="lagosSidebar"><div class="sidebar-head"><a class="brand" href="{{ route('dashboard') }}"><img src="{{ $siteLogo??asset('assets/img/logo-painel-branca.png') }}" alt="LagosPanel" class="logo-img" style="height:30px;width:auto;max-width:140px;object-fit:contain"><span class="brand-name">@if(config('app.name')==='LagosPanel')Lagos<b>Panel</b>@else{{ config('app.name') }}@endif</span></a></div><nav class="sidebar-nav">
@if(!request()->routeIs('admin.*'))
@php $nav=[['dashboard','home','Visão geral'],['services.index','server','Meus serviços'],['invoices.index','invoice','Minhas faturas'],['tickets.index','ticket','Suporte'],['ai.index','ticket','Chat com IA'],['store','store','Loja'],['profile','user','Minha conta'],['cart.index','cart','Carrinho'],['knowledge.index','book','Ajuda'],['api.index','api','Acesso à API'],['quotes.index','invoice','Orçamentos'],['downloads.index','book','Downloads'],['bulletins.index','clock','Avisos e status']]; @endphp
@foreach($nav as [$r,$icon,$label])<a href="{{ route($r) }}" class="nav-link {{ request()->routeIs($r) ? 'is-active' : '' }}">{!! panel_icon($icon,19) !!}<span>{{ $label }}</span></a>@endforeach
@if(auth()->user()->isStaff())<div class="nav-divider"></div><a class="nav-link" href="{{ route('admin.dashboard') }}">{!! panel_icon('shield',19) !!}<span>Administração</span></a>@endif
@endif
@if(request()->routeIs('admin.*') && auth()->user()->isStaff())<a class="nav-link" href="{{ route('dashboard') }}">{!! panel_icon('user',19) !!}<span>Área do cliente</span></a><div class="nav-divider"></div>@foreach([['settings.index','shield','Configurações'],['dashboard','chart','Administração'],['products','store','Produtos'],['invoices','invoice','Faturamento'],['services','server','Serviços'],['users','user','Clientes'],['tickets','ticket','Atendimento'],['coupons','card','Cupons'],['connectors','api','Integrações'],['operations','clock','Operações'],['audit','shield','Auditoria'],['team.index','user','Equipe'],['knowledge','book','Conhecimento'],['reports','chart','Relatórios'],['reviews','wallet','Conciliação'],['quotes.index','invoice','Orçamentos'],['bulletins.index','clock','Avisos e status'],['downloads.index','book','Downloads']] as [$r,$icon,$label])
@if(auth()->user()->hasPermission(\App\Support\AdminPermissions::forRoute('admin.'.$r)))<a href="{{ route('admin.'.$r) }}" class="nav-link {{ request()->routeIs($r==='settings.index'?'admin.settings.*':'admin.'.$r.'*')?'is-active':'' }}">{!! panel_icon($icon,19) !!}<span>{{ $label }}</span></a>@endif
@endforeach @endif
</nav><div class="sidebar-user"><div class="avatar">{{ mb_strtoupper(mb_substr(auth()->user()->name,0,1)) }}</div><div class="sidebar-user-meta"><strong>{{ auth()->user()->name }}</strong><span>{{ brl(auth()->user()->balance_minor) }}</span></div><form method="post" action="{{ route('logout') }}">@csrf<button class="icon-btn" title="Sair" aria-label="Sair">{!! panel_icon('logout',17) !!}</button></form></div></aside><div class="panel-overlay" id="lagosOverlay"></div><div class="panel-main"><header class="topbar"><button class="icon-btn menu-toggle" id="lagosMenuToggle" aria-label="Menu">{!! panel_icon('menu',20) !!}</button><h1 class="topbar-title">@yield('title')</h1><div class="topbar-actions"><button class="icon-btn" data-theme-toggle aria-label="Tema claro/escuro">{!! panel_icon('moon',18) !!}</button><a class="btn btn-ghost btn-sm" href="{{ route('store') }}">Loja</a></div></header><main class="panel-content">@include('layouts.flash')@yield('content')</main><footer class="panel-foot">@if(app()->environment('local'))Demonstração — dados fictícios · @endif
© {{ date('Y') }} — {{ config('app.name') }} · {{ config('lagos.version') }}</footer></div></div><script src="{{ asset('assets/panel.js') }}" defer></script><script src="{{ asset('assets/independent.js') }}" defer></script></body></html>