const puppeteer = require('puppeteer-core');
(async () => {
  const browser = await puppeteer.launch({ executablePath: '/usr/bin/chromium', headless: 'new', args: ['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--hide-scrollbars','--font-render-hinting=none'] });
  const page = await browser.newPage();
  await page.setViewport({ width: 1440, height: 900 });
  await page.goto('http://localhost:8080/termos-de-uso/', { waitUntil: 'networkidle0' });
  await new Promise((r) => setTimeout(r, 600));
  await page.screenshot({ path: '/home/user/lagospanel/screenshots/51-termos-de-uso.jpg', type: 'jpeg', quality: 85, fullPage: true });
  console.log('ok 51');
  await page.setViewport({ width: 360, height: 740, deviceScaleFactor: 2 });
  await page.goto('http://localhost:8080/politica-de-privacidade/', { waitUntil: 'networkidle0' });
  await new Promise((r) => setTimeout(r, 500));
  await page.screenshot({ path: '/home/user/lagospanel/screenshots/52-privacidade-mobile.jpg', type: 'jpeg', quality: 85, fullPage: true });
  console.log('ok 52');
  await page.setViewport({ width: 1440, height: 900 });
  await page.goto('http://localhost:8080/registrar/', { waitUntil: 'networkidle0' });
  await new Promise((r) => setTimeout(r, 500));
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
  console.log('overflow registrar desktop:', overflow);
  await page.screenshot({ path: '/home/user/lagospanel/screenshots/53-cadastro-lgpd.jpg', type: 'jpeg', quality: 85, fullPage: true });
  console.log('ok 53');
  await page.setViewport({ width: 360, height: 740, deviceScaleFactor: 2 });
  await page.goto('http://localhost:8080/registrar/', { waitUntil: 'networkidle0' });
  const ov2 = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
  console.log('overflow registrar 360px:', ov2);
  await browser.close();
})().catch((e) => { console.error('ERRO:', e.message); process.exit(1); });
